// Données des sessions de course — extraites des captures d'écran des applis.
// Allure en secondes/km pour permettre les calculs/graphiques.
// Durée en secondes. Distance en km. Dénivelé en m. FC en bpm. Cadence en spm.
//
// SEULES `date`, `duration`, `distance` et `paceSec` sont garanties. Tout le
// reste dépend de l'appli et de la montre du coureur, et le dashboard doit
// composer avec : Vincent et Anaïs sont sur Apple Fitness (FC, cadence,
// dénivelé, calories actives + totales), Didi sur adidas Running, qui ne donne
// ni FC, ni cadence, ni dénivelé, mais une vitesse de pointe (`maxSpeed`, km/h).
// Une clé absente n'est jamais remplacée par un zéro — un 0 bpm se lit comme une
// mesure, une clé manquante se lit comme « non mesuré ».
//
// `splits` (optionnel) : le détail kilomètre par kilomètre, lu sur la 2e capture
// (écran « Splits »). `sec` = temps passé sur ce tronçon, `paceSec` = allure
// ramenée au km — identiques sauf sur le dernier tronçon, incomplet (`partial`).
// Apple n'affiche FC et cadence par km que sur certaines montres : ces deux clés
// sont donc facultatives. Les séances d'avant août 2026 n'ont pas de splits.

const RUNS = {
  Vincent: [
    { date: "2026-05-16", duration: 1893, distance: 3.74, activeCal: 268, totalCal: 324, elevation: 13, cadence: 123, paceSec: 505, hr: 133 },
    { date: "2026-05-17", duration: 1877, distance: 3.80, activeCal: 268, totalCal: 322, elevation: 7,  cadence: 122, paceSec: 494, hr: 132 },
    { date: "2026-05-23", duration: 1844, distance: 3.79, activeCal: 261, totalCal: 315, elevation: 4,  cadence: 121, paceSec: 486, hr: 128 },
    { date: "2026-05-27", duration: 1918, distance: 3.72, activeCal: 258, totalCal: 314, elevation: 10, cadence: 121, paceSec: 515, hr: 127 },
    { date: "2026-05-30", duration: 1937, distance: 3.95, activeCal: 282, totalCal: 338, elevation: 6,  cadence: 123, paceSec: 490, hr: 135 },
    { date: "2026-06-09", duration: 1896, distance: 3.77, activeCal: 261, totalCal: 317, elevation: 6,  cadence: 124, paceSec: 503, hr: 135 },
    { date: "2026-06-11", duration: 1712, distance: 3.62, activeCal: 256, totalCal: 306, elevation: 9,  cadence: 126, paceSec: 472, hr: 137 },
    { date: "2026-06-14", duration: 1868, distance: 4.05, activeCal: 287, totalCal: 342, elevation: 10, cadence: 126, paceSec: 461, hr: 138 },
    { date: "2026-06-20", duration: 2124, distance: 4.63, activeCal: 334, totalCal: 396, elevation: 7,  cadence: 127, paceSec: 458, hr: 139 },
    { date: "2026-06-23", duration: 2053, distance: 4.55, activeCal: 327, totalCal: 387, elevation: 6,  cadence: 129, paceSec: 451, hr: 143 },
    { date: "2026-06-26", duration: 2180, distance: 4.84, activeCal: 346, totalCal: 410, elevation: 6,  cadence: 131, paceSec: 450, hr: 142 },
    { date: "2026-06-28", duration: 2286, distance: 5.15, activeCal: 367, totalCal: 434, elevation: 10, cadence: 132, paceSec: 443, hr: 144 },
    { date: "2026-07-01", duration: 2113, distance: 4.85, activeCal: 351, totalCal: 413, elevation: 8,  cadence: 134, paceSec: 435, hr: 149 },
    { date: "2026-07-05", duration: 2157, distance: 4.88, activeCal: 343, totalCal: 407, elevation: 9,  cadence: 131, paceSec: 442, hr: 138 },
    { date: "2026-07-07", duration: 2242, distance: 5.17, activeCal: 369, totalCal: 434, elevation: 6,  cadence: 134, paceSec: 433, hr: 148 },
    { date: "2026-07-10", duration: 1969, distance: 4.70, activeCal: 343, totalCal: 400, elevation: 6,  cadence: 137, paceSec: 419, hr: 143 },
    { date: "2026-07-17", duration: 2228, distance: 5.39, activeCal: 389, totalCal: 455, elevation: 10, cadence: 136, paceSec: 413, hr: 148 },
    { date: "2026-07-25", duration: 1985, distance: 5.04, activeCal: 373, totalCal: 431, elevation: 7,  cadence: 143, paceSec: 393, hr: 157 },
    { date: "2026-07-29", duration: 1944, distance: 5.01, activeCal: 372, totalCal: 428, elevation: 3,  cadence: 142, paceSec: 388, hr: 153 },
    { date: "2026-08-01", duration: 1926, distance: 5.01, activeCal: 376, totalCal: 432, elevation: 3,  cadence: 142, paceSec: 384, hr: 157 },
    { date: "2026-08-05", duration: 1881, distance: 5.01, activeCal: 375, totalCal: 430, elevation: 2,  cadence: 147, paceSec: 375, hr: 159 },
    { date: "2026-08-09", duration: 2345, distance: 6.01, activeCal: 463, totalCal: 531, elevation: 4,  cadence: 144, paceSec: 390, hr: 158,
      splits: [
        { km: 1, sec: 360, paceSec: 360, hr: 139, cadence: 154 },
        { km: 2, sec: 365, paceSec: 365, hr: 164, cadence: 153 },
        { km: 3, sec: 400, paceSec: 400, hr: 158, cadence: 140 },
        { km: 4, sec: 396, paceSec: 396, hr: 159, cadence: 141 },
        { km: 5, sec: 413, paceSec: 413, hr: 160, cadence: 140 },
        { km: 6, sec: 404, paceSec: 404, hr: 166, cadence: 143 },
        { km: 7, sec: 4,   paceSec: 365, hr: 174, cadence: 141, partial: true },
      ] },
    { date: "2026-08-12", duration: 1808, distance: 5.00, activeCal: 380, totalCal: 433, elevation: 5,  cadence: 153, paceSec: 362, hr: 163,
      splits: [
        { km: 1, sec: 351, paceSec: 351, hr: 147, cadence: 158 },
        { km: 2, sec: 359, paceSec: 359, hr: 164, cadence: 154 },
        { km: 3, sec: 374, paceSec: 374, hr: 162, cadence: 149 },
        { km: 4, sec: 384, paceSec: 384, hr: 164, cadence: 147 },
        { km: 5, sec: 339, paceSec: 339, hr: 177, cadence: 161 },
      ] },
    { date: "2026-08-19", duration: 1786, distance: 5.01, activeCal: 395, totalCal: 447, elevation: 5,  cadence: 156, paceSec: 356, hr: 165,
      splits: [
        { km: 1, sec: 372, paceSec: 372 },
        { km: 2, sec: 352, paceSec: 352 },
        { km: 3, sec: 362, paceSec: 362 },
        { km: 4, sec: 365, paceSec: 365 },
        { km: 5, sec: 328, paceSec: 328 },
        { km: 6, sec: 4,   paceSec: 278, partial: true },
      ] },
    { date: "2026-08-21", duration: 2214, distance: 6.03, activeCal: 472, totalCal: 537, elevation: 7,  cadence: 150, paceSec: 367, hr: 164,
      splits: [
        { km: 1, sec: 338, paceSec: 338, hr: 151, cadence: 160 },
        { km: 2, sec: 348, paceSec: 348, hr: 165, cadence: 154 },
        { km: 3, sec: 337, paceSec: 337, hr: 173, cadence: 158 },
        { km: 4, sec: 401, paceSec: 401, hr: 162, cadence: 143 },
        { km: 5, sec: 407, paceSec: 407, hr: 160, cadence: 140 },
        { km: 6, sec: 370, paceSec: 370, hr: 169, cadence: 158 },
        { km: 7, sec: 11,  paceSec: 374, hr: 177, cadence: 106, partial: true },
      ] },
    { date: "2026-08-26", duration: 1848, distance: 5.02, activeCal: 389, totalCal: 443, elevation: 4,  cadence: 158, paceSec: 368, hr: 161,
      splits: [
        { km: 1, sec: 370, paceSec: 370, hr: 141, cadence: 161 },
        { km: 2, sec: 374, paceSec: 374, hr: 159, cadence: 159 },
        { km: 3, sec: 362, paceSec: 362, hr: 166, cadence: 159 },
        { km: 4, sec: 374, paceSec: 374, hr: 166, cadence: 159 },
        { km: 5, sec: 352, paceSec: 352, hr: 173, cadence: 157 },
        { km: 6, sec: 14,  paceSec: 507, hr: 179, cadence: 141, partial: true },
      ] },
    { date: "2026-08-31", duration: 1761, distance: 5.02, activeCal: 377, totalCal: 428, elevation: 2,  cadence: 151, paceSec: 351, hr: 166,
      splits: [
        { km: 1, sec: 338, paceSec: 338, hr: 150, cadence: 161 },
        { km: 2, sec: 320, paceSec: 320, hr: 173, cadence: 158 },
        { km: 3, sec: 367, paceSec: 367, hr: 168, cadence: 145 },
        { km: 4, sec: 388, paceSec: 388, hr: 162, cadence: 141 },
        { km: 5, sec: 339, paceSec: 339, hr: 178, cadence: 155 },
        { km: 6, sec: 4,   paceSec: 179, hr: 183, cadence: 165, partial: true },
      ] },
  ],
  "Anaïs": [
    { date: "2026-05-17", duration: 1856, distance: 3.76, activeCal: 173, totalCal: 211, elevation: 5,  cadence: 129, paceSec: 493, hr: 131 },
    { date: "2026-05-23", duration: 1882, distance: 3.68, activeCal: 164, totalCal: 202, elevation: 3,  cadence: 129, paceSec: 511, hr: 118 },
    { date: "2026-05-27", duration: 1918, distance: 3.64, activeCal: 155, totalCal: 194, elevation: 10, cadence: 125, paceSec: 527, hr: 111 },
    { date: "2026-05-30", duration: 1939, distance: 3.88, activeCal: 175, totalCal: 214, elevation: 6,  cadence: 125, paceSec: 499, hr: 124 },
    { date: "2026-06-09", duration: 1895, distance: 3.66, activeCal: 169, totalCal: 207, elevation: 6,  cadence: 126, paceSec: 517, hr: 124 },
    { date: "2026-06-14", duration: 1868, distance: 3.87, activeCal: 177, totalCal: 215, elevation: 12, cadence: 126, paceSec: 482, hr: 125 },
    { date: "2026-06-20", duration: 2123, distance: 4.47, activeCal: 206, totalCal: 249, elevation: 9,  cadence: 130, paceSec: 474, hr: 127 },
    { date: "2026-06-28", duration: 2285, distance: 4.86, activeCal: 233, totalCal: 280, elevation: 8,  cadence: 131, paceSec: 470, hr: 129 },
    { date: "2026-07-05", duration: 2146, distance: 4.47, activeCal: 211, totalCal: 254, elevation: 5,  cadence: 130, paceSec: 480, hr: 130 },
    { date: "2026-07-10", duration: 1969, distance: 4.22, activeCal: 200, totalCal: 240, elevation: 9,  cadence: 133, paceSec: 467, hr: 125 },
    { date: "2026-07-17", duration: 2234, distance: 4.80, activeCal: 234, totalCal: 280, elevation: 9,  cadence: 130, paceSec: 465, hr: 136 },
    { date: "2026-07-29", duration: 1947, distance: 4.48, activeCal: 225, totalCal: 265, elevation: 5,  cadence: 138, paceSec: 434, hr: 142 },
    { date: "2026-08-01", duration: 1978, distance: 4.57, activeCal: 226, totalCal: 266, elevation: 2,  cadence: 138, paceSec: 432, hr: 144 },
    { date: "2026-08-09", duration: 2392, distance: 5.32, activeCal: 262, totalCal: 311, elevation: 3,  cadence: 138, paceSec: 449, hr: 145,
      splits: [
        { km: 1, sec: 406, paceSec: 406 },
        { km: 2, sec: 448, paceSec: 448 },
        { km: 3, sec: 443, paceSec: 443 },
        { km: 4, sec: 469, paceSec: 469 },
        { km: 5, sec: 478, paceSec: 478 },
        { km: 6, sec: 145, paceSec: 445, partial: true },
      ] },
    { date: "2026-08-12", duration: 1910, distance: 4.40, activeCal: 215, totalCal: 254, elevation: 5,  cadence: 144, paceSec: 434, hr: 141,
      splits: [
        { km: 1, sec: 407, paceSec: 407, hr: 133, cadence: 152 },
        { km: 2, sec: 451, paceSec: 451, hr: 136, cadence: 142 },
        { km: 3, sec: 441, paceSec: 441, hr: 141, cadence: 143 },
        { km: 4, sec: 428, paceSec: 428, hr: 151, cadence: 148 },
        { km: 5, sec: 179, paceSec: 446, hr: 157, cadence: 145, partial: true },
      ] },
    { date: "2026-08-19", duration: 1865, distance: 4.40, activeCal: 217, totalCal: 254, elevation: 5,  cadence: 149, paceSec: 423, hr: 149,
      splits: [
        { km: 1, sec: 422, paceSec: 422, hr: 127, cadence: 150 },
        { km: 2, sec: 426, paceSec: 426, hr: 147, cadence: 152 },
        { km: 3, sec: 418, paceSec: 418, hr: 156, cadence: 153 },
        { km: 4, sec: 421, paceSec: 421, hr: 158, cadence: 151 },
        { km: 5, sec: 173, paceSec: 424, hr: 169, cadence: 142, partial: true },
      ] },
    { date: "2026-08-26", duration: 2158, distance: 5.06, activeCal: 249, totalCal: 293, elevation: 3,  cadence: 146, paceSec: 426, hr: 144,
      splits: [
        { km: 1, sec: 420, paceSec: 420, hr: 126, cadence: 152 },
        { km: 2, sec: 437, paceSec: 437, hr: 140, cadence: 149 },
        { km: 3, sec: 431, paceSec: 431, hr: 146, cadence: 145 },
        { km: 4, sec: 445, paceSec: 445, hr: 147, cadence: 144 },
        { km: 5, sec: 399, paceSec: 399, hr: 164, cadence: 150 },
        { km: 6, sec: 23,  paceSec: 350, hr: 169, cadence: 135, partial: true },
      ] },
  ],
  // adidas Running : pas de FC, pas de cadence, pas de dénivelé. En revanche
  // une vitesse de pointe, et un seul chiffre de calories (pas de total).
  Didi: [
    { date: "2026-07-23", duration: 1971, distance: 5.00, activeCal: 347, paceSec: 394, maxSpeed: 11.0 },
    { date: "2026-07-26", duration: 1989, distance: 5.02, activeCal: 349, paceSec: 396, maxSpeed: 10.9 },
    { date: "2026-07-30", duration: 1951, distance: 5.02, activeCal: 347, paceSec: 388, maxSpeed: 10.6 },
    { date: "2026-08-01", duration: 1945, distance: 5.01, activeCal: 348, paceSec: 388, maxSpeed: 10.4 },
    { date: "2026-08-05", duration: 1902, distance: 5.01, activeCal: 347, paceSec: 379, maxSpeed: 13.9 },
    { date: "2026-08-09", duration: 1889, distance: 5.00, activeCal: 345, paceSec: 377, maxSpeed: 11.2 },
  ],
  // Ju a rejoint le dashboard mais n'a pas encore déposé de capture : le tableau
  // vide lui réserve sa place (carte, filtre, couleur) au lieu de la faire
  // apparaître au milieu de la première séance.
  Ju: [],
};

const RUNNER_COLORS = {
  Vincent: "#0a84ff",
  "Anaïs": "#ff375f",
  Didi: "#30d158",
  Ju: "#bf5af2",
};

// Analyses « coach » par séance, rédigées en comparant chaque run aux précédentes
// du MÊME coureur (jamais de mélange Vincent / Anaïs).
// trend : "up" (progrès) | "flat" (stable / volontairement facile) | "down" (en retrait) | "start" (1re séance)
// Contexte coureurs : Vincent 30 ans, Anaïs 29 ans — 9 ans de musculation chacun, très novices en cardio.
//
// `text` : un TABLEAU de paragraphes `{ titre, texte }`, une idée par entrée (le
// constat chiffré, ce que disent les splits, le conseil). Le dashboard rend un
// intertitre + un <p> par élément — un bloc unique de dix phrases n'est pas lu,
// surtout sur téléphone, et les titres donnent le fil à qui parcourt en diagonale.
// Titre : 2 à 6 mots qui disent quelque chose, jamais le verdict recopié.
//
// `pokemon` : le nom français d'un Pokémon de la 1re génération (voir pokemon.js).
// Section purement humoristique : le rang de vitesse aide à choisir mais n'est
// plus affiché. Un même Pokémon ne sert qu'une fois par coureur — chacun se
// constitue son Pokédex — mais rien n'interdit qu'il serve aussi à quelqu'un d'autre.
// `pokemonAdj` : l'adjectif qui personnalise la créature (« Persian Impérial »),
// pris dans POKEMON_ADJECTIFS ou inventé. Jamais deux fois le même par coureur.
// `pokemonPhrase` : la vanne, qui justifie le Pokémon ET son adjectif.
const ANALYSES = {
  Vincent: {
    "2026-05-16": { trend: "start", verdict: "Point de départ",
      text: [
        { titre: "La ligne de base", texte: "Première séance enregistrée : 3,74 km en 8'25\"/km à 133 bpm. C'est ta ligne de base." },
        { titre: "Le cardio, chantier numéro un", texte: "Avec 9 ans de muscu dans les jambes mais un cardio encore neuf, l'objectif des prochaines semaines n'est pas la vitesse mais d'habituer le cœur et le souffle à l'effort continu." },
      ],
      pokemon: "Chenipan", pokemonAdj: "Frétillant",
      pokemonPhrase: "Chenipan, 45 en vitesse : personne ne commence sa carrière en Dracaufeu. La bonne nouvelle, c'est qu'il évolue vite. Frétillant, parce que frétiller est à peu près tout ce qu'une chenille sait faire — et pour un premier jour, c'était amplement suffisant." },
    "2026-05-17": { trend: "up", verdict: "Déjà plus rapide",
      text: [
        { titre: "11 s/km en deux jours", texte: "Deux jours seulement après la première sortie, et déjà 11 s/km de gagnées (8'14\" contre 8'25\") pour une fréquence cardiaque identique. Enchaîner si vite montre une bonne récupération — un héritage direct de ton entraînement en force." },
      ],
      pokemon: "Machopeur", pokemonAdj: "Poussif",
      pokemonPhrase: "Machopeur : quatre bras taillés par neuf ans de fonte, deux jambes qui découvrent le concept de cardio. On connaît quelqu'un. Poussif, parce que le souffle n'a visiblement pas reçu le mémo que les bras avaient depuis neuf ans." },
    "2026-05-23": { trend: "up", verdict: "Cœur plus efficace",
      text: [
        { titre: "128 bpm à allure égale", texte: "Allure encore grignotée (8'06\"/km), mais surtout la FC moyenne baisse à 128 bpm alors que tu cours aussi vite." },
        { titre: "Le premier signe d'adaptation", texte: "Le cœur travaille moins pour le même effort : c'est le premier vrai signe d'adaptation aérobie. Continue comme ça." },
      ],
      pokemon: "Métamorph", pokemonAdj: "Assoupli",
      pokemonPhrase: "Métamorph : sa seule compétence au monde, c'est de s'adapter. Ton cœur vient de faire exactement ça — 128 bpm à la même allure. Assoupli, parce que passer de 133 à 128 bpm sans rien demander à personne, c'est de la souplesse à l'état pur." },
    "2026-05-27": { trend: "flat", verdict: "Séance en souplesse",
      text: [
        { titre: "Une séance facile assumée", texte: "Sortie plus tranquille : 8'35\"/km, la plus lente jusqu'ici, sur une distance raccourcie. Ta FC est au plus bas (127 bpm), donc c'est une séance facile assumée, pas un coup de moins bien." },
        { titre: "L'endurance se construit là", texte: "Ces sorties en aisance construisent l'endurance autant que les rapides." },
      ],
      pokemon: "Ronflex", pokemonAdj: "Placide",
      pokemonPhrase: "Ronflex, 30 en vitesse et zéro complexe. 127 bpm de moyenne : tu as couru dans le même état d'esprit, et c'était le bon choix. Placide, parce que 127 bpm en pleine course, c'est à peu près sa fréquence cardiaque au réveil." },
    "2026-05-30": { trend: "up", verdict: "Rebond + distance record",
      text: [
        { titre: "Rebond et record de distance", texte: "Joli rebond : retour à 8'10\"/km et surtout ta plus longue distance à ce jour (3,95 km), tu frôles la barre des 4 km." },
        { titre: "Tenir l'effort plus longtemps", texte: "Les calories montent avec le volume. Tu commences à tenir l'effort plus longtemps." },
      ],
      pokemon: "Grodoudou", pokemonAdj: "Élastique",
      pokemonPhrase: "Grodoudou : on l'écrase, il rebondit, et il revient toujours un peu plus gros. 3,95 km, ton record — rebond validé. Élastique, parce que trois jours après une sortie molle tu ressors avec un record : ça rebondit tout seul." },
    "2026-06-09": { trend: "flat", verdict: "Reprise après coupure",
      text: [
        { titre: "Retour après dix jours", texte: "Reprise après 10 jours de coupure : 8'23\"/km, un poil en retrait, ce qui est parfaitement normal après une pause." },
        { titre: "Le temps de retrouver le rythme", texte: "La FC reste un peu haute pour l'allure, le temps de retrouver le rythme. L'essentiel est d'être reparti." },
      ],
      pokemon: "Soporifik", pokemonAdj: "Groggy",
      pokemonPhrase: "Soporifik : dix jours de sieste, un réveil forcément pâteux. L'essentiel est qu'il ait rouvert les yeux. Groggy, parce qu'à 8'23 au kilomètre, on voit bien que le café n'a pas encore fait effet." },
    "2026-06-11": { trend: "up", verdict: "Première sous les 8'/km",
      text: [
        { titre: "Sous les 8'/km", texte: "Cap symbolique franchi : première sortie sous les 8'/km (7'52\") !" },
        { titre: "Court et rapide, un choix", texte: "Tu as raccourci la distance pour pousser l'allure, et signé ta séance la plus courte en durée (28:32). La vitesse pure progresse nettement." },
      ],
      pokemon: "Mackogneur", pokemonAdj: "Dégourdi",
      pokemonPhrase: "Mackogneur : le Machopeur du 17 mai a évolué. Une paire de bras en plus, et surtout une première sortie sous les 8'/km. Dégourdi, parce qu'avec quatre bras et un cardio tout neuf, il a très vite compris de quel côté se trouvait la marge de progression." },
    "2026-06-14": { trend: "up", verdict: "Plus vite ET plus loin",
      text: [
        { titre: "Les deux à la fois", texte: "Du costaud : plus vite (7'41\"/km) ET plus loin (4,05 km, nouveau record de distance) dans la même séance." },
        { titre: "Le moteur cardio se construit", texte: "D'habitude on gagne sur l'un en lâchant sur l'autre — là tu progresses sur les deux. Le moteur cardio se construit pour de bon." },
      ],
      pokemon: "Caninos", pokemonAdj: "Increvable",
      pokemonPhrase: "Caninos : petit chien increvable qui court plus vite ET plus loin sans jamais se poser la question. Le résumé exact de ta séance. Increvable, parce que gagner sur l'allure ET sur la distance le même jour, c'est le programme d'un chien que personne n'a prévenu que c'était censé être difficile." },
    "2026-06-20": { trend: "up", verdict: "Cap des 4,5 km",
      text: [
        { titre: "Record de distance", texte: "Gros bond d'endurance : 4,63 km, ton record, en gardant une allure de 7'38\"/km." },
        { titre: "35 minutes tenues", texte: "Plus de 35 min d'effort continu et 334 cal brûlées. Le cœur monte à 139 bpm mais tient la distance — exactement la progression attendue." },
      ],
      pokemon: "Lokhlass", pokemonAdj: "Débonnaire",
      pokemonPhrase: "Lokhlass : sa spécialité, c'est de transporter les gens sur de longues distances sans jamais s'énerver. 4,63 km à 139 bpm — même contrat. Débonnaire, parce que 35 minutes d'effort continu sans jamais hausser le ton, c'est exactement sa fiche de poste." },
    "2026-06-23": { trend: "up", verdict: "Record d'allure",
      text: [
        { titre: "Record d'allure, cadence en hausse", texte: "Nouveau record d'allure : 7'31\"/km sur 4,55 km, avec une cadence qui grimpe (129 spm), signe d'une foulée plus efficace. Tu cours désormais près d'une minute par km plus vite qu'à tes débuts de mai." },
      ],
      pokemon: "Salamèche", pokemonAdj: "Fumant",
      pokemonPhrase: "Salamèche : la flamme au bout de la queue vient de s'allumer. Premier vrai record d'allure, ça commence à chauffer. Fumant, parce qu'une cadence à 129 spm, c'est la mèche qui prend enfin." },
    "2026-06-26": { trend: "up", verdict: "Presque 5 km",
      text: [
        { titre: "À 160 mètres des 5 km", texte: "Tout proche des 5 km : 4,84 km, record de distance, à 7'30\"/km (record d'allure égalé) et meilleure cadence (131 spm)." },
        { titre: "Le palier est à portée", texte: "Distance et vitesse continuent de monter ensemble. Le palier des 5 km est à portée de main." },
      ],
      pokemon: "Goupix", pokemonAdj: "Frustré",
      pokemonPhrase: "Goupix : il naît avec six queues et il lui en manque trois pour être complet. Il te manquait 160 mètres. On compatit sincèrement. Frustré, parce qu'il lui manque éternellement trois queues, et à toi 160 mètres. Vous vous comprenez." },
    "2026-06-28": { trend: "up", verdict: "Premier 5 km 🎉",
      text: [
        { titre: "Le premier 5 km", texte: "Le voilà, ton premier 5 km : 5,15 km en 7'23\"/km, record sur les deux tableaux !" },
        { titre: "Six semaines de chemin", texte: "En six semaines tu es passé de 3,7 km à 8'25\" à un vrai 5K à 7'23\". Pour un cardio parti de zéro, c'est une progression remarquable — ton fond musculaire a clairement accéléré l'adaptation." },
      ],
      pokemon: "Papilusion", pokemonAdj: "Triomphant",
      pokemonPhrase: "Papilusion : la chenille du 16 mai a terminé son évolution, et elle vole. Premier 5 km — c'était écrit depuis le premier jour. Triomphant, parce qu'on ne passe pas six semaines en chrysalide pour rater son premier 5 km." },
    "2026-07-01": { trend: "up", verdict: "Record d'allure",
      text: [
        { titre: "Record d'allure, gaz à fond", texte: "Nouveau record d'allure : 7'15\"/km, soit 8 s/km de mieux que ton précédent meilleur (7'23\"). Sur une distance un peu plus courte (4,85 km), tu as clairement mis le gaz — FC à 149 bpm, ta plus haute, et cadence record de 134 spm." },
        { titre: "Distance d'abord, vitesse ensuite", texte: "Après ton premier 5 km, tu travailles maintenant la vitesse : les deux se complètent parfaitement." },
      ],
      pokemon: "Piafabec", pokemonAdj: "Teigneux",
      pokemonPhrase: "Piafabec : minuscule, teigneux, il fonce sans jamais calculer sa dépense. FC record à 149 bpm — le portrait craché. Teigneux, parce que monter à 149 bpm sur 4,85 km, c'est l'attitude d'un oiseau de deux kilos qui va provoquer un Dracaufeu." },
    "2026-07-05": { trend: "flat", verdict: "Séance en aisance",
      text: [
        { titre: "Même distance, 11 bpm de moins", texte: "Retour à une allure plus tranquille (7'22\"/km) sur une distance quasi identique (4,88 km) à ton record du 1er juillet — mais avec 11 bpm de moins (138 contre 149)." },
        { titre: "Lever le pied, à propos", texte: "C'est le signe qu'après ta séance de vitesse, tu as sagement levé le pied : le cœur encaisse un effort proche pour un coût cardiaque bien moindre, preuve que l'adaptation continue même les jours plus faciles." },
      ],
      pokemon: "Tentacool", pokemonAdj: "Nonchalant",
      pokemonPhrase: "Tentacool : il ne rame pas, il se laisse porter par le courant. 138 bpm quatre jours après une séance à 149 — très bien joué. Nonchalant, parce que quatre jours après avoir tout donné, il s'est contenté de flotter dans le bon sens — et c'était la bonne décision." },
    "2026-07-07": { trend: "up", verdict: "Double record !",
      text: [
        { titre: "Distance et allure d'un coup", texte: "Grosse séance : nouveau record de distance (5,17 km, ton premier vrai dépassement du 5K) ET nouveau record d'allure (7'13\"/km, 2 s/km de mieux que ton précédent record) dans la même sortie." },
        { titre: "Tout donné, et ça se voit", texte: "FC à 148 bpm, cadence au sommet (134 spm) — tu as clairement tout donné (effort ressenti « Hard »)." },
        { titre: "Deux semaines après le 5 km", texte: "Deux semaines après ton premier 5 km, tu cours maintenant plus loin ET plus vite en même temps : la progression s'accélère." },
      ],
      pokemon: "Dardargnan", pokemonAdj: "Survolté",
      pokemonPhrase: "Dardargnan ne connaît qu'un seul réglage : plein gaz. Double record et effort ressenti « Hard », il n'aurait pas fait autrement. Survolté, parce que « effort ressenti Hard » est la seule case qu'il sache cocher." },
    "2026-07-10": { trend: "up", verdict: "Record d'allure... en mode facile",
      text: [
        { titre: "Sous les 7'/km, sans forcer", texte: "Le plus bluffant : nouveau record d'allure (6'59\"/km, 14 s/km de mieux que ton précédent record de mardi), sous la barre symbolique des 7'/km, mais avec un effort ressenti « Moderate » (contre « Hard » la dernière fois) et une FC plus basse (143 contre 148). Cadence record aussi (137 spm)." },
        { titre: "L'allure record devient confortable", texte: "Ce qui était une allure à fond il y a encore quelques semaines devient une allure confortable — c'est exactement la marque d'une vraie adaptation cardio." },
      ],
      pokemon: "Reptincel", pokemonAdj: "Décontracté",
      pokemonPhrase: "Reptincel : Salamèche a évolué et la flamme ne vacille plus. Sous les 7'/km, et en ressenti « Moderate » par-dessus le marché. Décontracté, parce qu'il fait passer pour une promenade ce qui était encore un plafond quinze jours plus tôt. Le Salamèche du 23 juin appréciera modérément." },
    "2026-07-17": { trend: "up", verdict: "Encore un double record",
      text: [
        { titre: "Double record au retour", texte: "Après une semaine de pause, tu reviens avec un double record : plus longue distance à ce jour (5,39 km) ET meilleure allure (6'53\"/km, 6 s/km de mieux que ton record du 10 juillet). Le tout ressenti « Moderate » malgré une FC à 148 bpm sur plus de 37 minutes d'effort." },
        { titre: "Deux mois, deux courbes qui montent", texte: "Deux mois après tes débuts à 3,7 km en 8'25\", tu enchaînes les sorties où distance et vitesse montent ensemble — la marge de progression est loin d'être épuisée." },
      ],
      pokemon: "Kicklee", pokemonAdj: "Infatigable",
      pokemonPhrase: "Kicklee : un Pokémon qui, fondamentalement, n'est que deux jambes. Difficile de faire plus adapté à un double record en course à pied. Infatigable, parce qu'un Pokémon dépourvu de bras, de tronc et d'opinions n'a rien d'autre à faire de sa journée que d'allonger la foulée." },
    "2026-07-25": { trend: "up", verdict: "Record pulvérisé : 6'33\"/km",
      text: [
        { titre: "20 s/km d'un coup", texte: "Ce n'est plus une progression, c'est un bond : 6'33\"/km, soit 20 s/km arrachées à ton record du 17 juillet — de loin ton plus gros saut d'allure depuis le début. Tu boucles tes 5 km en 33:05, ta séance la plus rapide sur cette distance, avec une cadence record de 143 spm (+7 d'un coup) : ta foulée est nettement plus vive." },
        { titre: "157 bpm, le prix payé", texte: "La FC à 157 bpm est la plus haute jamais enregistrée, donc tu es allé chercher loin — d'où l'intérêt de faire suivre celle-ci d'une sortie en aisance." },
        { titre: "Deux minutes gagnées depuis mai", texte: "Repère du chemin parcouru : le 16 mai tu courais à 8'25\"/km, tu as gagné près de 2 minutes par kilomètre en dix semaines." },
      ],
      pokemon: "Colossinge", pokemonAdj: "Furibond",
      pokemonPhrase: "Colossinge : il part à fond, il s'énerve, et il ne redescend jamais. 157 bpm, ta FC la plus haute — l'état d'esprit y était. Furibond, parce qu'on ne gratte pas 20 s/km d'un coup en restant courtois." },
    "2026-07-29": { trend: "up", verdict: "Nouveau record… ressenti « Easy »",
      text: [
        { titre: "Plus vite, moins fatigué", texte: "La séance la plus parlante depuis tes débuts : encore un record d'allure (6'28\"/km, 5 s/km de mieux que le 25 juillet) et ton 5 km le plus rapide à ce jour (32:24), mais cette fois avec un effort ressenti « Easy » et une FC en baisse (153 contre 157 bpm). Aller plus vite en se fatiguant moins, c'est le signal d'adaptation le plus net qu'on puisse avoir." },
        { titre: "La foulée vive est devenue la norme", texte: "Ta cadence se stabilise à un haut niveau (142 spm) : la foulée vive du 25 juillet n'était pas un accident, elle est devenue ta norme." },
        { titre: "Ton allure facile d'aujourd'hui", texte: "Deux mois et demi après tes 8'25\"/km du 16 mai, ton allure de course facile est désormais plus rapide que ton allure maximale de juin." },
      ],
      pokemon: "Feunard", pokemonAdj: "Hautain",
      pokemonPhrase: "Feunard : les neuf queues, enfin au complet. Goupix galérait pour finir ses 5 km, lui bat son record en trouvant ça « Easy ». Hautain, parce que courir plus vite en se fatiguant moins et ne pas en faire toute une histoire, c'est du mépris tranquille — et il maîtrise le genre." },
    "2026-08-01": { trend: "up", verdict: "Trois records d'allure d'affilée",
      text: [
        { titre: "Troisième record consécutif", texte: "Troisième record consécutif : 6'24\"/km, 4 s/km de mieux que le 29 juillet, sur exactement la même distance (5,01 km) — 18 secondes de moins sur le chrono, ton 5 km le plus rapide à ce jour (32:06)." },
        { titre: "Des gains plus fins, bon signe", texte: "Les gains se resserrent après le bond de 20 s/km du 25 juillet, et c'est plutôt bon signe : tu n'es plus en phase de rattrapage, tu grattes des secondes sur une base déjà solide." },
        { titre: "Le point à surveiller", texte: "Seul point à surveiller, la FC remonte à 157 bpm (contre 153) alors que le ressenti reste « Easy » — trois séances rapides en une semaine, ça mérite une sortie franchement lente pour laisser l'adaptation se fixer." },
      ],
      pokemon: "Rapasdepic", pokemonAdj: "Obstiné",
      pokemonPhrase: "Rapasdepic : une fois qu'il a verrouillé sa cible, il ne lâche plus rien. Troisième record d'allure d'affilée, on va finir par te croire. Obstiné, parce que trois records d'affilée sur la même distance, ça ne s'appelle plus de l'entraînement, ça s'appelle du harcèlement de chronomètre." },
    "2026-08-05": { trend: "up", verdict: "Quatrième record d'affilée : 6'15\"/km",
      text: [
        { titre: "45 secondes en quatre jours", texte: "Quatre records consécutifs, et pas le plus petit : 6'15\"/km, 9 s/km de mieux que le 1er août sur exactement la même distance (5,01 km) — ton 5 km passe sous les 31:30 (31:21), soit 45 secondes gagnées en quatre jours." },
        { titre: "La vitesse vient de la cadence", texte: "La cadence signe un nouveau sommet à 147 spm (+5 d'un coup), et c'est bien là que la vitesse est allée se chercher : une foulée plus vive, pas des enjambées plus longues." },
        { titre: "Le bémol, en plus marqué", texte: "Un bémol quand même, le même que la dernière fois en plus marqué : la FC monte encore, 159 bpm, ta plus haute jamais enregistrée, et tu n'as toujours pas placé la sortie lente que je te suggérais." },
        { titre: "La consigne : une vraie sortie lente", texte: "Quatre séances rapides d'affilée, ça finit par se payer — la prochaine, vise franchement l'aisance (autour de 7'/km, FC sous 145). Ça ne cassera rien de ce que tu as construit, au contraire : c'est ce qui permettra au record suivant d'arriver." },
      ],
      pokemon: "Dodrio", pokemonAdj: "Frénétique",
      pokemonPhrase: "Dodrio : trois têtes, six pattes, une cadence de machine à coudre. À 147 spm, tu joues officiellement dans sa catégorie. Frénétique, parce qu'à 147 pas par minute, ses trois têtes ont depuis longtemps cessé de se consulter." },
    "2026-08-09": { trend: "up", verdict: "Premier 6 km 🎉",
      text: [
        { titre: "Sorti de la boucle des 5 km", texte: "Tu es sorti de la boucle des 5 km : 6,01 km, soit 620 m de plus que ton précédent record du 17 juillet — de loin ta plus grosse marche de distance depuis le début. C'est aussi ta séance la plus longue (39:05, tu bats le 38:06 du 28 juin) et la plus coûteuse en énergie (463 cal actives contre 389 au maximum jusqu'ici)." },
        { titre: "Une allure qui ne se compare pas", texte: "L'allure de 6'30\"/km paraît en retrait de tes 6'15\" du 5 août, mais ça ne se compare pas : sur ta dernière sortie de plus de 5,2 km, le 17 juillet, tu tournais à 6'53\" — tu viens de courir 620 m de plus, 23 s/km plus vite." },
        { titre: "Le départ payé sur quatre kilomètres", texte: "Là où il y a vraiment à apprendre, c'est dans tes splits : 6'00\" et 6'05\" sur les deux premiers kilomètres, c'est-à-dire plus vite que ton allure record sur 5 km, puis 6'40\", 6'36\", 6'53\", 6'44\" — près de 50 s/km perdues, et une FC qui grimpe de 139 à 174 bpm sur la fin. Tu as payé le départ pendant quatre kilomètres. Sur une distance nouvelle, pars 20 à 30 s/km plus lentement que ton allure cible : tu finiras plus vite, et sans doute plus loin." },
        { titre: "La sortie lente, troisième rappel", texte: "Et je repose la même question pour la troisième fois — la sortie lente. Cinq séances de qualité d'affilée, FC moyenne encore à 158 bpm, effort ressenti « Hard » : tu construis vite, mais tu ne laisses jamais l'adaptation se poser. La prochaine, 45 minutes à 7'15\"/km, FC sous 145, sans regarder la montre." },
      ],
      pokemon: "Électrode", pokemonAdj: "Impatient",
      pokemonPhrase: "Électrode : le Pokémon le plus rapide de la première génération, et le seul dont l'attaque signature s'appelle Explosion. Deux kilomètres à 6'00 de moyenne, puis boum au troisième. On ne pouvait pas mieux résumer. Impatient, parce que 6'00 au premier kilomètre d'une distance jamais courue, c'est très exactement le genre d'initiative qui se termine en Explosion." },
    "2026-08-12": { trend: "up", verdict: "Record : le 5 km en 30:08",
      text: [
        { titre: "13 s/km de mieux que le 5 août", texte: "5,00 km en 30:08, soit 6'02\"/km : 13 s/km de mieux que le 6'15\" du 5 août, et 1 min 13 de moins au chrono sur la distance. C'est ton cinquième record d'allure depuis le 25 juillet, et de loin la plus grosse marche depuis cette date — les précédentes valaient 5, 4 et 9 s/km. La cadence moyenne signe elle aussi un sommet, 153 spm, +6 d'un coup." },
        { titre: "Un vrai finish, pour une fois", texte: "Le dernier kilomètre est passé en 5'39\", à 177 bpm et 161 spm : le plus rapide de tous tes kilomètres chronométrés, et l'exact inverse du 9 août, où la fin s'effondrait à 6'44\". Tu avais donc une cartouche en réserve après quatre kilomètres — c'est une information précieuse." },
        { titre: "Les kilomètres 3 et 4, encore", texte: "Le défaut, lui, n'a pas bougé : 5'51\" et 5'59\" au départ, puis 6'14\" et 6'24\" — 33 s/km lâchées entre le 1er et le 4e kilomètre, avec une cadence qui glisse de 158 à 147 spm. La différence, c'est que ce 5'39\" final prouve que ce n'était pas la fatigue, mais la gestion. Quatre kilomètres tenus à 6'05\" et le même dernier kilomètre, ça fait 29:59 : les 30 minutes ne demandent qu'un départ plus sage." },
        { titre: "163 bpm, quatrième rappel", texte: "Et pour la quatrième fois : la sortie lente. FC moyenne à 163 bpm, ta plus haute jamais enregistrée, avec un pic à 177 sur la fin — six séances de qualité d'affilée sans une seule sortie facile. Ça finit toujours par plafonner, quand ça ne casse pas. La prochaine : 45 minutes à 7'15\"/km, FC sous 145, montre dans la poche." },
      ],
      pokemon: "Galopa", pokemonAdj: "Fougueux",
      pokemonPhrase: "Galopa : un cheval de feu qui passe sa vie à provoquer en course tout ce qui bouge, et dont on dit qu'il ne montre sa vraie vitesse que le jour où ça l'arrange. Quatre kilomètres de trot poli, puis 5'39 sur le dernier — ça l'arrangeait. Fougueux, parce que garder ta plus belle accélération pour le moment où il ne reste plus un mètre à courir, ce n'est pas une tactique, c'est un tempérament." },
    "2026-08-19": { trend: "up", verdict: "Le 5 km sous les 30 minutes 🎉",
      text: [
        { titre: "Le calcul du 12 août tenait", texte: "Il y a une semaine j'écrivais : quatre kilomètres tenus à 6'05\" et le même dernier kilomètre, ça fait 29:59, les 30 minutes ne demandent qu'un départ plus sage. Tu as fait très exactement ça, et tu passes en 29:46 — 13 secondes sous le calcul. 5,01 km à 5'56\"/km, sixième record d'allure depuis le 25 juillet, 6 s/km de mieux que le 12 août." },
        { titre: "21 secondes lâchées au départ", texte: "Le premier kilomètre passe en 6'12\", contre 5'51\" la semaine dernière. C'est la première fois depuis le début que tu pars volontairement plus lentement que ton allure cible, et c'est toute la séance qui change de forme. Sur la même distance, tu as gagné 22 secondes au chrono en partant 21 secondes plus lentement — retiens ce chiffre, il vaut tous les discours." },
        { titre: "Les kilomètres 3 et 4 ne lâchent plus", texte: "Le défaut que je te signalais depuis trois séances a disparu. 6'12\", 5'52\", 6'02\", 6'05\" : sept secondes séparent ton premier kilomètre du quatrième, et dans le bon sens. Le 12 août tu en lâchais 33 sur ce même segment, le 9 août près de 50. Ce n'était donc ni la forme ni la fatigue, c'était la gestion — la démonstration est faite." },
        { titre: "Le dernier kilomètre en 5:28", texte: "Et il restait de la marge : 5'28\" sur le dernier kilomètre complet, le plus rapide que tu aies jamais chronométré (le précédent record était le 5'39\" du 12 août), puis les derniers mètres sur un rythme de 4'38\". Deux séances de suite que tu finis plus vite que tu ne commences. La cadence moyenne suit, 156 spm, encore un sommet." },
        { titre: "165 bpm, cinquième rappel", texte: "Maintenant la partie qui va moins te plaire. FC moyenne à 165 bpm, ta plus haute jamais enregistrée — encore une fois — et effort ressenti « Hard ». Ça fait sept séances de qualité d'affilée, et cinq fois que je te demande la même chose. Je ne trouverai pas de formulation plus convaincante que les quatre précédentes, alors je vais le dire autrement : la seule variable de ton entraînement que tu n'aies jamais testée, c'est le repos." },
        { titre: "Ce que je veux voir la prochaine", texte: "45 minutes à 7'15\"/km, FC sous 145, montre dans la poche. Pas un record, pas un test, pas un 6 km. Tu viens de prouver qu'un départ maîtrisé valait 22 secondes ; le corollaire, c'est qu'une semaine contenant une vraie sortie facile vaut probablement le record suivant. Après ça, on ira chercher les 29 minutes." },
      ],
      pokemon: "Dracaufeu", pokemonAdj: "Flamboyant",
      pokemonPhrase: "Dracaufeu : Salamèche le 23 juin, Reptincel le 10 juillet, et l'évolution finale pile pour ton premier 5 km sous les 30 minutes. Deux mois pour boucler la chaîne, c'est le rythme d'un dresseur sérieux. Flamboyant, parce qu'un dernier kilomètre en 5'28 après quatre autres tenus au cordeau, ce n'est pas une arrivée, c'est une sortie de scène." },
    "2026-08-21": { trend: "up", verdict: "Record sur 6 km : 36:54",
      text: [
        { titre: "La bonne référence : le 9 août", texte: "6,03 km en 36:54, soit 6'07\"/km. La comparaison qui compte n'est pas celle du 19 août — 5,01 km à 5'56\", ce n'est pas la même course — mais celle de ta seule autre sortie de 6 km, le 9 août : 39:05 à 6'30\"/km. Douze jours plus tard, tu reprends 2 min 11 au chrono et 23 s/km sur la même distance. Cinq de tes six kilomètres complets sont passés plus vite que ce jour-là, et le quatrième ne concède que 5 secondes." },
        { titre: "63 secondes prises au 3e kilomètre", texte: "Kilomètre par kilomètre, face au 9 août : −22 s, −17 s, −63 s, +5 s, −6 s, −34 s. Le troisième est le grand écart de la séance — 6'40\" ce jour-là, 5'37\" aujourd'hui — et c'est aussi celui où tu montes à 173 bpm, ta FC la plus haute de la sortie hors tronçon final. Tu n'as pas couru le même 6 km en mieux : tu as couru les trois premiers kilomètres comme un 5 km de record, plus vite encore que le 5'56\" du 19 août." },
        { titre: "70 secondes entre le km 3 et le km 5", texte: "La facture arrive au quatrième : 6'41\", puis 6'47\". Soixante-dix secondes au kilomètre séparent ton troisième de ton cinquième, le plus grand écart de tous tes relevés de splits — le précédent était de 53 secondes, le 9 août. La cadence raconte la même chose, 158 spm au troisième kilomètre, 140 au cinquième : ce n'est pas l'allure qui a baissé, c'est la foulée qui s'est décrochée, et la FC qui redescend à 160 pendant que tu ralentis le confirme." },
        { titre: "Le positive split fond de 12 secondes", texte: "Le progrès de fond est là, lui aussi : entre ton premier et ton dernier kilomètre complet, tu lâchais 44 secondes le 9 août, tu n'en lâches plus que 32. Et tu finis en accélérant — 6'10\" sur le sixième, 37 s/km repris sur le cinquième, cadence remontée à 158 spm. Troisième séance d'affilée que tu termines plus vite que l'avant-dernier kilomètre : tu avais donc encore de quoi courir à 6'10\" au moment où tu tournais à 6'47\"." },
        { titre: "164 bpm, sixième rappel", texte: "Un point pour toi quand même : 164 bpm de moyenne contre 158 le 9 août, pour 23 s/km plus vite sur la même distance, et l'effort ressenti passe de « Hard » à « Moderate ». L'adaptation est mesurable, elle est réelle. Ça reste huit séances de qualité d'affilée, et six fois que je te réclame la même chose. Le repos est toujours la seule variable de ton entraînement que tu n'aies jamais testée." },
        { titre: "Ce que je veux voir la prochaine", texte: "D'abord la sortie lente qu'on se promet depuis un mois : 45 minutes à 7'15\"/km, FC sous 145, montre dans la poche. Ensuite, quand tu reviendras sur 6 km, garde ce calcul en tête — quatre kilomètres à 6'00\" et deux à 6'10\", ça fait 36:31, soit 23 secondes de mieux qu'aujourd'hui sans jamais passer par le mur du quatrième. Le 19 août, le même calcul s'était vérifié à 13 secondes près." },
      ],
      pokemon: "Rhinocorne", pokemonAdj: "Inarrêtable",
      pokemonPhrase: "Rhinocorne : il charge tout droit, et le Pokédex précise que son cerveau est si petit qu'il en oublie en route pourquoi il s'est élancé. Trois kilomètres à 5'40 de moyenne sur une sortie de 6 km, on tient la démonstration. Inarrêtable, parce que le seul moment où tu as vraiment freiné, c'est le kilomètre 4 — et ce n'est pas toi qui as pris la décision." },
    "2026-08-26": { trend: "flat", verdict: "Cadence record, effort « Easy »",
      text: [
        { titre: "Pas de chrono à battre", texte: "5,02 km en 30:48, soit 6'08\"/km : 12 s/km au-dessus de ton record du 19 août, et c'est la première fois depuis le 25 juillet que tu ne pars pas chercher une performance. L'effort ressenti repasse à « Easy », ce qui n'était plus arrivé depuis le 1er août — sauf que ce jour-là, « Easy » valait 6'24\"/km. Ton allure confortable a gagné 16 s/km en vingt-cinq jours." },
        { titre: "Vingt-deux secondes d'amplitude", texte: "6'10\", 6'14\", 6'02\", 6'14\", 5'52\" : vingt-deux secondes séparent ton kilomètre le plus rapide du plus lent, et quatre secondes seulement le premier du quatrième. C'est de loin la séance la plus régulière de tous tes relevés de splits — l'amplitude était de 44 secondes le 19 août, de 45 le 12 août et de 70 le 21 août." },
        { titre: "Jamais plus de quatre pas d'écart", texte: "161, 159, 159, 159, 157 spm. Ta foulée ne perd jamais plus de quatre pas par minute sur toute la sortie, et la moyenne signe un sommet à 158 spm. Le 21 août, elle glissait de 158 à 140 entre le troisième et le cinquième kilomètre, et c'est très exactement là que la séance s'était écroulée. Ce décrochage a disparu : c'est le vrai progrès du jour, bien plus que le chrono." },
        { titre: "22 s/km plus vite pour 3 bpm", texte: "La comparaison qui résume le mois : le 9 août tu courais à 6'30\"/km pour 158 bpm et un effort « Hard ». Aujourd'hui, 6'08\"/km pour 161 bpm et un effort « Easy ». Vingt-deux secondes au kilomètre de mieux, trois battements de plus, et le ressenti qui passe de dur à facile — en dix-sept jours. L'adaptation aérobie n'est plus une hypothèse." },
        { titre: "Et il restait de la marge", texte: "5'52\" sur le cinquième kilomètre, le plus rapide de la séance, à 173 bpm et 157 spm. C'est la quatrième sortie d'affilée où ton dernier kilomètre complet va plus vite que l'avant-dernier. Une séance annoncée facile qui se termine par son meilleur kilomètre, ça veut dire que le réservoir était encore loin d'être vide." },
        { titre: "161 bpm, septième rappel", texte: "Reste le point qui ne bouge pas. « Easy » au sens d'Apple n'est pas la sortie lente que je te réclame depuis le 1er août : 161 bpm de moyenne, un pic à 179, et neuf séances d'affilée sans une seule sortie en récupération. Tu as appliqué la moitié de la consigne, celle qui consistait à ne pas viser un record, et laissé de côté l'autre, qui est la seule à faire quelque chose pour ton cœur. 45 minutes à 7'15\"/km, FC sous 145. Après ça, on ira chercher les 29 minutes." },
      ],
      pokemon: "Insécateur", pokemonAdj: "Méthodique",
      pokemonPhrase: "Insécateur : ses lames vont si vite qu'on ne voit jamais le geste, seulement le résultat, et le Pokédex insiste sur la précision plutôt que sur la puissance. Quatre kilomètres dans un mouchoir de douze secondes et une cadence qui ne varie jamais de plus de quatre pas, c'est de la découpe au millimètre. Méthodique, parce qu'il faut une certaine rigueur pour n'appliquer très exactement que la moitié d'une consigne donnée six fois." },
    "2026-08-31": { trend: "up", verdict: "Record : le 5 km en 29:21",
      text: [
        { titre: "25 secondes reprises au 19 août", texte: "5,02 km en 29:21, soit 5'51\"/km : septième record d'allure depuis le 25 juillet, 5 s/km de mieux que le 5'56\" du 19 août, et 25 secondes reprises au chrono sur la distance. Deuxième passage sous les 30 minutes, et cette fois avec de la marge." },
        { titre: "5'20 au deuxième kilomètre", texte: "Le deuxième kilomètre est passé en 5'20\" : le plus rapide de tout ton historique de splits, huit secondes devant le 5'28\" du 19 août. Kilomètre par kilomètre face à ce jour-là : −34 s, −32 s, +5 s, +23 s, +11 s. Après deux kilomètres tu avais 66 secondes d'avance sur ton propre record ; tu en as rendu 39 sur les trois suivants." },
        { titre: "Le décrochage était en vacances", texte: "Puis 6'07\" et 6'28\". Soixante-huit secondes séparent ton kilomètre le plus rapide du plus lent, la deuxième plus grosse amplitude de tous tes relevés — le record reste les 70 secondes du 21 août. La cadence raconte la même histoire : 158 spm au deuxième kilomètre, 141 au quatrième, vingt pas par minute évaporés. Le 26 août elle ne bougeait jamais de plus de quatre pas, et je t'écrivais que ce décrochage avait disparu. Il était juste en vacances." },
        { titre: "Dix centimètres de foulée en plus", texte: "Le détail qui compte : ta cadence moyenne tombe à 151 spm, sept pas sous le sommet du 26 août, et tu cours pourtant 17 s/km plus vite. Le calcul est sans appel — environ 4 430 pas aujourd'hui contre 4 870 le 26 août pour la même distance, soit 1,13 m par foulée contre 1,03 m. Depuis le 5 août, ta vitesse venait de la fréquence des pas ; celle-ci vient de leur longueur. C'est un mécanisme neuf, et il vaut d'être noté." },
        { titre: "Les 29 minutes étaient là", texte: "Reprends ces splits en remplaçant les deux du milieu par un honnête 6'00\" — pas 5'20\", juste 6'00\" — et le chrono tombe à 28:41. Même en y collant tes kilomètres 3 et 4 du 19 août, ceux d'une séance pourtant moins rapide, tu passes en 28:48. Tu n'as donc pas besoin d'aller plus vite pour aller chercher les 29 minutes : tu as besoin de ne pas passer le deuxième kilomètre à 5'20\"." },
        { titre: "« All Out », huitième rappel", texte: "Reste le point qui ne bouge pas. Effort ressenti « All Out », le premier de tout ton historique, FC moyenne à 166 bpm — encore un sommet — et un pic à 183 sur les derniers mètres. Dix séances de qualité d'affilée, huit fois que je te réclame la même chose. Alors je vais cesser de la formuler comme une punition : la sortie lente n'est pas le prix de ce que tu viens de faire, c'est ce qui rend le prochain 28 possible. 45 minutes à 7'15\"/km, FC sous 145, montre dans la poche." },
      ],
      pokemon: "Arcanin", pokemonAdj: "Incorrigible",
      pokemonPhrase: "Arcanin : le Caninos du 14 juin a fini par évoluer, et le Pokédex lui prête 10 000 km en 24 heures sans jamais faiblir. Toi, tu as tenu sa légende pendant exactement 5 minutes et 20 secondes. Incorrigible, parce qu'il aura fallu huit demandes de sortie lente pour obtenir le premier « All Out » de ton historique." },
  },
  "Anaïs": {
    "2026-05-17": { trend: "start", verdict: "Point de départ",
      text: [
        { titre: "La référence de départ", texte: "Première séance enregistrée : 3,76 km en 8'13\"/km à 131 bpm. C'est ta référence de départ." },
        { titre: "Le cœur d'abord, la vitesse ensuite", texte: "Comme pour toute débutante en cardio venant de la force, le plan est simple : laisser le cœur et le souffle s'habituer avant de chercher la vitesse." },
      ],
      pokemon: "Évoli", pokemonAdj: "Indécis",
      pokemonPhrase: "Évoli : rien n'est encore décidé, toutes les évolutions restent ouvertes. C'est très exactement la définition d'une première séance. Indécis, parce qu'après une seule séance, absolument toutes les évolutions sont encore sur la table." },
    "2026-05-23": { trend: "flat", verdict: "Effort mieux dosé",
      text: [
        { titre: "13 bpm de moins qu'au départ", texte: "L'allure ralentit un peu (8'31\"/km), mais regarde la FC : 118 bpm, soit 13 de moins qu'à la première sortie. Tu apprends à doser ton effort plutôt qu'à tout donner — exactement la bonne approche pour bâtir une base aérobie solide." },
      ],
      pokemon: "Machoc", pokemonAdj: "Raisonnable",
      pokemonPhrase: "Machoc : neuf ans à soulever de la fonte, et il découvre qu'on peut aussi bouger pendant trente minutes d'affilée. 118 bpm — il a compris avant tout le monde qu'il fallait doser. Raisonnable, parce que perdre 13 bpm en une séance, c'est une sagesse qu'on n'attend pas d'un Pokémon dont l'unique passe-temps est de soulever des rochers." },
    "2026-05-27": { trend: "flat", verdict: "Séance tout en contrôle",
      text: [
        { titre: "111 bpm, ta FC la plus basse", texte: "Séance tout en contrôle : 8'47\"/km, mais une FC moyenne de seulement 111 bpm, ta plus basse. Tu cours en grande aisance respiratoire." },
        { titre: "Les fondations de l'endurance", texte: "Ces sorties faciles ne paient pas tout de suite au chrono, mais elles posent les fondations de l'endurance." },
      ],
      pokemon: "Ramoloss", pokemonAdj: "Serein",
      pokemonPhrase: "Ramoloss : 15 en vitesse, dernier des 151, et parfaitement heureux comme ça. 111 bpm de moyenne, tu as couru dans sa zone de confort — et c'était le bon plan. Serein, parce qu'à ce rythme cardiaque, on a surtout le temps de réfléchir à ce qu'on va manger ce soir." },
    "2026-05-30": { trend: "up", verdict: "Accélération + record",
      text: [
        { titre: "28 s/km et un record", texte: "Belle accélération : 8'19\"/km (28 s/km de gagnées) sur ta plus longue distance à ce jour (3,88 km). La FC remonte logiquement à 124 bpm puisque tu pousses davantage." },
        { titre: "La base se transforme en vitesse", texte: "Tu commences à transformer la base construite en vitesse." },
      ],
      pokemon: "Minidraco", pokemonAdj: "Ambitieux",
      pokemonPhrase: "Minidraco : personne ne le prend au sérieux, et il finit en Dracolosse. Record de distance et 28 s/km grattées, la trajectoire est lancée. Ambitieux, parce qu'après une séance pareille, il exige déjà qu'on l'appelle par son nom d'évolution finale." },
    "2026-06-09": { trend: "flat", verdict: "Reprise après coupure",
      text: [
        { titre: "Reprise après dix jours", texte: "Reprise après 10 jours sans courir : 8'37\"/km, un léger retrait bien normal après une coupure. Distance et FC restent dans tes standards." },
        { titre: "La machine est relancée", texte: "L'essentiel est d'avoir relancé la machine — la forme revient vite." },
      ],
      pokemon: "Kokiyas", pokemonAdj: "Boudeur",
      pokemonPhrase: "Kokiyas : dix jours coquille fermée, il la rouvre sans en faire un drame. Reprendre, c'est déjà la moitié du travail. Boudeur, parce qu'il a rouvert sa coquille, mais il tenait à faire savoir que ces dix jours n'étaient absolument pas de sa faute." },
    "2026-06-14": { trend: "up", verdict: "Record d'allure",
      text: [
        { titre: "35 s/km d'un coup", texte: "Record d'allure : 8'02\"/km, soit 35 s/km de mieux que la séance précédente, ta meilleure performance jusqu'ici." },
        { titre: "Même effort, plus de vitesse", texte: "Et tout ça à FC quasi inchangée (125 bpm) : le même effort te fait désormais aller bien plus vite. L'adaptation cardio porte ses fruits." },
      ],
      pokemon: "Roucool", pokemonAdj: "Guilleret",
      pokemonPhrase: "Roucool : le premier envol. 35 s/km d'un coup et une FC qui ne bronche pas — il est petit, mais il vient clairement de décoller. Guilleret, parce qu'un progrès pareil sans le moindre surcoût cardiaque, ça met de bonne humeur même un oiseau de niveau 3." },
    "2026-06-20": { trend: "up", verdict: "Sous 8' et cap des 4 km",
      text: [
        { titre: "Deux caps le même jour", texte: "Double cap franchi : ta première sortie sous les 8'/km (7'54\") et ton record de distance (4,47 km, +0,6 km d'un coup)." },
        { titre: "Distance et vitesse ensemble", texte: "Plus de 35 min d'effort, 206 cal. Distance et vitesse progressent ensemble — pour un cardio parti de novice, la marche est nette." },
      ],
      pokemon: "Roucoups", pokemonAdj: "Conquérant",
      pokemonPhrase: "Roucoups : Roucool a évolué. Première sortie sous les 8'/km et record de distance dans la foulée, il monte en régime. Conquérant, parce qu'après un premier envol réussi, il a décidé que la barre des 8'/km lui appartenait." },
    "2026-06-28": { trend: "up", verdict: "Double record",
      text: [
        { titre: "Plus loin, plus vite", texte: "Double record d'un coup : 4,86 km (ta plus longue distance) à 7'50\"/km (ta meilleure allure, 4 s/km de mieux que le 20 juin)." },
        { titre: "129 bpm seulement", texte: "Et tout ça pour seulement 129 bpm de moyenne, à peine plus qu'avant : tu cours désormais plus loin ET plus vite sans que le cœur s'emballe. Le cap des 5 km est à portée." },
      ],
      pokemon: "Lamantine", pokemonAdj: "Imperturbable",
      pokemonPhrase: "Lamantine : elle avale les kilomètres au chaud sans jamais emballer son cœur. 4,86 km, meilleure allure, 129 bpm — même méthode exactement. Imperturbable, parce que battre deux records à 129 bpm, c'est courir avec le pouls de quelqu'un qui fait la sieste." },
    "2026-07-05": { trend: "down", verdict: "Petit coup de mou",
      text: [
        { titre: "Une séance plus difficile", texte: "Séance plus difficile : distance en retrait (4,47 km contre 4,86 km) et allure ralentie (8'00\"/km contre 7'50\"), pour une FC quasi identique (130 bpm)." },
        { titre: "Un creux parfaitement normal", texte: "Après deux belles sorties records, ce genre de petit passage à vide est normal — le corps encaisse et régule sa charge d'entraînement. Rien d'inquiétant, la tendance de fond reste très positive." },
      ],
      pokemon: "Psykokwak", pokemonAdj: "Migraineux",
      pokemonPhrase: "Psykokwak : il a mal au crâne, il ne sait pas bien pourquoi, et ça finit toujours par passer. Un coup de mou, ça arrive même aux meilleurs. Migraineux, parce que c'est son état par défaut, et que ça ne l'a jamais empêché de se présenter à la séance suivante." },
    "2026-07-10": { trend: "up", verdict: "Record d'allure au petit matin",
      text: [
        { titre: "Record avec un cœur plus calme", texte: "Le coup de mou du 5 juillet est déjà oublié : record d'allure à 7'47\"/km (3 s/km de mieux que ton précédent record du 28 juin), et surtout avec une FC de seulement 125 bpm, bien plus basse que tes dernières sorties à 129-130." },
        { titre: "L'adaptation aérobie, en clair", texte: "Courir plus vite avec un cœur plus calme, c'est la définition même de l'adaptation aérobie. La cadence record (133 spm) montre aussi une foulée qui s'affine." },
      ],
      pokemon: "Aquali", pokemonAdj: "Fluide",
      pokemonPhrase: "Aquali : tout en fluidité, rien en force. Un record d'allure à 125 bpm, c'est très précisément sa signature. Fluide, parce qu'un chrono pareil ne s'arrache pas : il se laisse glisser." },
    "2026-07-17": { trend: "up", verdict: "Encore un record d'allure",
      text: [
        { titre: "Meilleure allure, plus longtemps", texte: "Deuxième record d'allure d'affilée : 7'45\"/km, sur une distance bien plus longue que la semaine dernière (4,80 km, tout proche de ton record de 4,86 km)." },
        { titre: "Ce qui a changé en un mois", texte: "Tu tiens maintenant ta meilleure allure sur quasi 5 km — il y a un mois, elle n'était possible que sur des sorties plus courtes. La FC monte logiquement à 136 bpm avec le volume, mais le cap des 5 km à cette allure est clairement à ta portée." },
      ],
      pokemon: "Doduo", pokemonAdj: "Têtu",
      pokemonPhrase: "Doduo : deux têtes, deux pattes, et aucune notion de l'arrêt. Meilleure allure tenue sur près de 5 km — il approuve. Têtu, parce qu'avec deux têtes, il a mathématiquement deux fois plus d'occasions de refuser de s'arrêter." },
    "2026-07-29": { trend: "up", verdict: "Énorme bond : 7'14\"/km",
      text: [
        { titre: "31 s/km arrachées", texte: "Ton plus gros saut d'allure depuis le début : 7'14\"/km, soit 31 s/km arrachées à ton record du 17 juillet — après des progrès qui se comptaient en 3 ou 4 secondes, tu viens de franchir une marche entière. La cadence explose au passage (138 spm, +5 sur ton précédent record) : c'est là qu'est venue la vitesse, une foulée bien plus vive plutôt que des enjambées forcées." },
        { titre: "Une séance de vitesse assumée", texte: "La FC à 142 bpm est la plus haute que tu aies enregistrée et la distance est volontairement plus courte (4,48 km) : c'était une séance de vitesse assumée, à faire suivre d'une sortie en aisance." },
        { titre: "Une minute par km en dix semaines", texte: "Le chemin parcouru fait plaisir à voir — le 17 mai tu courais à 8'13\"/km, tu as gagné près d'une minute par kilomètre en dix semaines." },
      ],
      pokemon: "Taupiqueur", pokemonAdj: "Jaillissant",
      pokemonPhrase: "Taupiqueur : il ne progresse pas, il jaillit du sol d'un coup. 31 s/km en une seule séance, dans le jeu ça s'appelle Tunnel. Jaillissant, parce que 31 s/km d'un coup, ça ne s'appelle pas progresser, ça s'appelle sortir de terre." },
    "2026-08-01": { trend: "up", verdict: "Le bond du 29 juillet confirmé",
      text: [
        { titre: "Le progrès s'est installé", texte: "La question après ton énorme saut du 29 juillet était : est-ce que ça tient ? Réponse oui — nouveau record d'allure à 7'12\"/km (2 s/km de mieux), et cette fois sur une distance plus longue (4,57 km contre 4,48). Tenir sa meilleure allure sur plus de terrain, c'est la vraie preuve qu'un progrès s'est installé plutôt qu'un bon jour isolé." },
        { titre: "La foulée est devenue automatique", texte: "La cadence reste calée à 138 spm et la FC bouge à peine (144 contre 142) : ta foulée vive est devenue automatique." },
        { titre: "Ce que disent les splits", texte: "Tes splits racontent bien la séance — départ à 6'51\", puis stabilisation autour de 7'12-7'26\" : tu es partie un peu vite, essaie de lisser sur la prochaine, tu finiras plus fraîche." },
      ],
      pokemon: "Rattatac", pokemonAdj: "Trépidant",
      pokemonPhrase: "Rattatac : de toutes petites pattes, une fréquence de dingue, et il double tout le monde. 138 spm confirmés — la foulée vive est devenue la tienne. Trépidant, parce que 138 pas par minute sur des pattes de cette taille, ça relève davantage de la machine à coudre que de la course à pied." },
    "2026-08-09": { trend: "up", verdict: "Premier 5 km 🎉",
      text: [
        { titre: "Le premier 5 km", texte: "Ça y est, le cap est passé : 5,32 km, ton premier vrai 5 km, et 460 m de plus que ton record du 28 juin qui tenait depuis six semaines. C'est aussi ta plus longue séance (39:52, contre 38:05 en juin) et la plus dépensière (262 cal actives, ton précédent maximum était à 234)." },
        { titre: "L'allure était le bon choix", texte: "L'allure de 7'29\"/km est en retrait de tes 7'12\" du 1er août, et c'est exactement ce qu'il fallait faire : sur ta dernière sortie longue, le 28 juin, tu tournais à 7'50\" sur 4,86 km — tu viens de courir 460 m de plus, 21 s/km plus vite." },
        { titre: "Le détail qui compte : la cadence", texte: "Le détail qui compte le plus à mes yeux : ta cadence tient à 138 spm, identique à tes deux dernières séances, alors que tu as couru près de 8 minutes de plus. Quand la fatigue arrive, la foulée est la première chose qui s'écroule chez une coureuse encore jeune en cardio — la tienne n'a pas bougé." },
        { titre: "145 bpm, et trois mois de chemin", texte: "La FC à 145 bpm est ta plus haute, mais sur presque 40 minutes d'effort c'est cohérent, rien d'alarmant. Trois mois après tes 3,76 km à 8'13\"/km du 17 mai, tu cours 40 % plus loin et 44 s/km plus vite." },
        { titre: "Le vrai reproche : les splits", texte: "Le seul vrai reproche, et c'est déjà celui du 1er août : tes splits. 6'46\" sur le premier kilomètre — plus rapide que ta meilleure allure moyenne à ce jour — puis 7'28\", 7'23\", 7'49\" et 7'58\" : tu perds 1'12\"/km entre ton premier et ton avant-dernier kilomètre, là où l'écart n'était que de 35 s la dernière fois. La consigne de lisser était déjà passée, et le trou s'est creusé au lieu de se réduire." },
        { titre: "La consigne pour la suite", texte: "Pour la suite, ne cherche pas à allonger tout de suite : refais deux ou trois fois cette distance en passant le premier kilomètre autour de 7'40\". Ça te paraîtra beaucoup trop lent pendant cinq minutes, et tu finiras plus vite qu'aujourd'hui — c'est comme ça que le 6 km viendra tout seul." },
      ],
      pokemon: "Roucarnage", pokemonAdj: "Impétueux",
      pokemonPhrase: "Roucarnage : Roucool en juin, Roucoups en juillet, l'évolution finale pile pour ton premier 5 km. Reste à lui apprendre à ne pas tout donner dès le premier battement d'ailes. Impétueux, parce que 6'46 au premier kilomètre, c'est l'évolution finale qui découvre ses ailes et oublie qu'il en reste quatre autres à parcourir." },
    "2026-08-12": { trend: "up", verdict: "Record de cadence : 144 spm",
      text: [
        { titre: "Six pas par minute de plus", texte: "Ta cadence était calée à 138 spm depuis le 29 juillet, sur trois séances d'affilée. Elle passe à 144 d'un coup. Le reste de la séance suit : 7'14\"/km, à 2 s de ton record du 1er août, pour 141 bpm seulement — moins que tes trois dernières sorties. Et tu as gardé la distance courte trois jours après ton premier 5 km, ce qui était exactement la consigne." },
        { titre: "Le départ rapide est toujours là", texte: "6'47\" sur le premier kilomètre. La consigne du 9 août était de le passer autour de 7'40\", et c'est la troisième fois que je te la donne. Sur ce point précis, rien n'a bougé." },
        { titre: "Mais la fin ne s'écroule plus", texte: "C'est là que la séance devient intéressante. Le 9 août, tes kilomètres partaient de 6'46\" pour finir à 7'58\" : une dégringolade continue de 1'12\". Aujourd'hui c'est 6'47\", 7'31\", 7'21\", 7'08\" — tu encaisses le contrecoup sur le deuxième kilomètre, puis tu réaccélères, et ton dernier kilomètre complet est le deuxième plus rapide de la séance. L'écart tombe de 1'12\" à 21 s." },
        { titre: "Ce que le premier kilomètre a coûté", texte: "La facture est dans la FC. 133 bpm pour courir en 6'47\", puis 151 bpm pour courir en 7'08\" : sur le quatrième kilomètre, tu vas 21 s/km moins vite avec 18 battements de plus. La courbe ne redescend jamais — 133, 136, 141, 151, 157. Voilà ce qu'un départ trop rapide fait payer pendant toute la séance, même quand les jambes suivent." },
        { titre: "La foulée, elle, tient bon", texte: "Cadence par kilomètre : 152, 142, 143, 148, 145. Elle remonte sur la fin au lieu de s'effondrer, et c'est cohérent avec ton quatrième kilomètre accéléré. La foulée vive n'est plus un effort ponctuel, elle revient toute seule quand tu pousses." },
        { titre: "Un dernier essai sur le premier km", texte: "Refais très exactement cette séance, mais passe le premier kilomètre à 7'40\". Avec la cadence que tu tiens maintenant, tu devrais finir sous les 7'/km sur le dernier — et à une FC qui ne sera jamais montée à 157. C'est le seul verrou qui te reste." },
      ],
      pokemon: "Colossinge", pokemonAdj: "Increvable",
      pokemonPhrase: "Colossinge : il s'emballe au premier regard de travers et ne redescend plus jamais. Ta FC a fait exactement ça — 133 bpm au premier kilomètre, 157 à l'arrivée, pas un battement rendu en chemin. Increvable, parce que boucler son quatrième kilomètre plus vite que son deuxième avec 18 battements de plus au compteur, c'est un entêtement que personne ne pourra lui retirer." },
    "2026-08-19": { trend: "up", verdict: "Le verrou a sauté",
      text: [
        { titre: "45 secondes sur le même parcours", texte: "Même distance au mètre près qu'il y a une semaine (4,40 km), même dénivelé, même boucle : le 12 août tu mettais 31:50, aujourd'hui 31:05. 45 secondes gagnées sur un terrain identique, c'est la comparaison la plus honnête qui existe. L'allure moyenne tombe à 7'03\"/km — record, 9 s/km de mieux que tes 7'12\" du 1er août." },
        { titre: "15 secondes lâchées au départ", texte: "Trois séances de suite que je te demandais de ralentir ton premier kilomètre. Tu l'as passé en 7'02\" au lieu de 6'47\" — pas les 7'40\" que je réclamais, mais 15 secondes rendues. Et tu as fini la séance 45 secondes plus vite. C'est très exactement le mécanisme que la consigne visait : ce que tu ne dépenses pas dans les cinq premières minutes, tu le récupères plusieurs fois derrière." },
        { titre: "Quatre kilomètres dans un mouchoir", texte: "7'02\", 7'06\", 6'58\", 7'01\". Huit secondes séparent ton kilomètre le plus rapide du plus lent, et le meilleur des quatre est le troisième. Le 12 août, l'écart entre premier et dernier kilomètre complet était de 21 secondes ; le 9 août, de 1'12\". Aujourd'hui : une seconde. Tu ne cours plus vite au début et lentement à la fin, tu cours à une allure." },
        { titre: "La cadence ne décroche plus", texte: "149 spm de moyenne, +5 sur ton record de la semaine dernière. Par kilomètre : 150, 152, 153, 151. Le creux a disparu — le 12 août ta cadence tombait à 142 dès le deuxième kilomètre avant de remonter en fin de séance. Une foulée qui reste à 150 pendant quatre kilomètres d'affilée, c'est précisément ce qui rend cette régularité possible." },
        { titre: "La facture : 169 bpm à l'arrivée", texte: "La FC moyenne monte à 149 bpm, ta plus haute à ce jour. Par kilomètre : 127, 147, 156, 158, puis 169 sur le tronçon final. Le départ est plus calme que la semaine dernière (127 contre 133), mais la montée est ensuite plus marquée. C'est le prix normal d'une allure tenue plutôt que subie, et sur 31 minutes d'effort il n'y a rien là qui doive t'inquiéter." },
        { titre: "Maintenant, rallonge", texte: "Le problème de gestion est réglé sur 4,4 km : à cette distance, je n'ai plus rien à corriger. La prochaine marche est la longueur. Reprends les 5,3 km du 9 août — ceux que tu avais courus à 7'29\" en t'écroulant sur la fin — et applique la gestion d'aujourd'hui à la lettre : premier kilomètre autour de 7'05\", pas une seconde plus vite. Tu devrais passer sous les 7'20\" de moyenne, et surtout finir en tenant." },
      ],
      pokemon: "Magnéton", pokemonAdj: "Métronomique",
      pokemonPhrase: "Magnéton : trois Magnéti verrouillés ensemble, qui avancent sans qu'aucun des trois ne prenne jamais les devants. 7'02\", 7'06\", 6'58\", 7'01\" — huit secondes d'amplitude sur toute la séance, c'est du vol en formation. Métronomique, parce qu'après quatre kilomètres tu repasses à une seconde de ton point de départ : à ce niveau-là on ne court plus, on bat la mesure." },
    "2026-08-26": { trend: "up", verdict: "Ton kilomètre le plus rapide, en dernier",
      text: [
        { titre: "La consigne appliquée à la lettre", texte: "Le 19 août je te demandais trois choses : rallonger, passer le premier kilomètre autour de 7'05\" et descendre sous 7'20\" de moyenne. Tu as couru 5,06 km — 660 m de plus que la semaine dernière — avec un premier kilomètre en 7'00\" et une moyenne de 7'06\"/km. Les trois cases sont cochées, et la troisième avec 14 secondes d'avance." },
        { titre: "23 s/km de mieux que le 9 août", texte: "La comparaison qui compte est celle de ton autre sortie de 5 km, le 9 août : 5,32 km à 7'29\"/km. Aujourd'hui, 7'06\"/km. Vingt-trois secondes au kilomètre reprises en dix-sept jours sur une distance équivalente. Et ton record d'allure du 19 août (7'03\") tenait sur 4,40 km : tu viens de courir 660 m de plus pour 3 s/km seulement." },
        { titre: "6'39\" au cinquième kilomètre", texte: "C'est le kilomètre le plus rapide que tu aies jamais couru. Ton précédent meilleur était le 6'46\" du 9 août, et c'était le premier de la séance ; celui-ci arrive à la trentième minute. Puis tu boucles les derniers mètres sur un rythme de 5'50\". Le défaut qui te suivait depuis juillet n'est pas seulement corrigé, il est retourné." },
        { titre: "Du positive au negative split", texte: "Regarde la série : le 9 août tu lâchais 1'12\" entre ton premier et ton dernier kilomètre complet, le 12 août 21 secondes, le 19 août une seconde. Aujourd'hui tu en reprends 21. Tu ne te contentes plus de tenir ton allure, tu finis plus vite que tu n'as commencé — et sur ta plus longue sortie depuis le 9 août." },
        { titre: "144 bpm, ta FC la plus basse du mois", texte: "126, 140, 146, 147, puis 164 sur le kilomètre accéléré. Quatre kilomètres passés entre 126 et 147 bpm, et une moyenne de 144 : plus bas que le 19 août (149) et que le 9 août (145), alors que tu cours plus loin que le premier et plus vite que le second. La montée n'arrive qu'au moment où tu décides d'accélérer, ce qui est exactement l'ordre normal des choses." },
        { titre: "Le trou du quatrième kilomètre", texte: "Il reste un point, et un seul : 7'25\" au quatrième, ton kilomètre le plus lent. Ce n'est pas la fatigue, la FC y est à 147 bpm, deux battements au-dessus du troisième. C'est la cadence : 152, 149, 145, 144, puis 150 dès que tu relances. Ta foulée se ramollit de huit pas par minute avant que l'allure ne baisse, et elle revient intacte dès que tu pousses. Ce n'est pas une question de moyens, c'est une question d'attention." },
        { titre: "La consigne : 148 spm au 4e km", texte: "Refais cette distance et surveille un seul chiffre, la cadence de ton quatrième kilomètre. Objectif 148 spm, pas moins. Tu as prouvé aujourd'hui que tu savais courir à 150 spm après 28 minutes d'effort : il s'agit juste de ne plus attendre le cinquième kilomètre pour y penser. Avec ce trou comblé, tu passes sous les 7'/km sur 5 km, et ce sera mérité." },
      ],
      pokemon: "Triopikeur", pokemonAdj: "Sournois",
      pokemonPhrase: "Triopikeur : Taupiqueur savait déjà jaillir du sol d'un coup, mais à trois on peut se permettre d'attendre son moment. Quatre kilomètres passés sagement sous terre, puis 6'39 au cinquième, le plus rapide que tu aies jamais couru. Sournois, parce que sortir sa meilleure allure à la trentième minute, ce n'est plus une fin de course, c'est une embuscade." },
  },
  // adidas Running ne remonte ni FC ni cadence : les analyses de Didi s'appuient
  // sur ce qui est mesuré — allure, régularité, temps de pause, vitesse de pointe.
  Didi: {
    "2026-07-23": { trend: "start", verdict: "Point de départ",
      text: [
        { titre: "Une ligne de base solide", texte: "Première séance enregistrée : 5,00 km en 32:51, soit 6'34\"/km à 9,1 km/h de moyenne. C'est ta ligne de base, et elle est d'emblée solide — un 5 km complet dès la première sortie, sans passer par les distances intermédiaires." },
        { titre: "Ce qu'on suivra chez toi", texte: "Ton appli ne remonte ni fréquence cardiaque ni cadence : on suivra donc l'allure, la régularité et le temps de pause. Le chrono sera le juge de paix, et sur un parcours identique à chaque fois, c'est même la mesure la plus honnête qui soit." },
      ],
      pokemon: "Porygon", pokemonAdj: "Méthodique",
      pokemonPhrase: "Porygon : un Pokémon entièrement programmé, incapable de faire deux fois la même chose différemment. 5,00 km pile au premier essai, on ne pouvait pas mieux tomber. Méthodique, parce qu'un résultat aussi rond ne s'improvise pas : il se compile." },
    "2026-07-26": { trend: "flat", verdict: "Copie conforme",
      text: [
        { titre: "La photocopie à deux secondes", texte: "Trois jours plus tard, la photocopie : 5,02 km en 33:09, 6'36\"/km — 2 s/km d'écart avec la séance précédente, soit l'épaisseur du trait. Vitesse de pointe quasi identique elle aussi (10,9 contre 11,0 km/h)." },
        { titre: "Une régularité qui rassure", texte: "À ce stade, cette régularité est une bonne nouvelle plutôt qu'une stagnation : elle dit que l'allure du 23 juillet n'était pas un jour de forme isolé mais ton vrai rythme de croisière. C'est une base fiable, et c'est de là qu'on ira chercher du mieux." },
      ],
      pokemon: "Excelangue", pokemonAdj: "Consciencieux",
      pokemonPhrase: "Excelangue : sa langue fait deux fois la longueur de son corps et il ne s'en sert jamais pour aller plus vite. Deux secondes au kilomètre en dix-sept jours, il aurait fait pareil. Consciencieux, parce que refaire la même séance à deux secondes près, c'est du travail d'orfèvre — ou d'une langue étalonnée au décimètre." },
    "2026-07-30": { trend: "up", verdict: "Premier record : 6'28\"/km",
      text: [
        { titre: "Premier vrai gain", texte: "Premier vrai gain : 6'28\"/km, 8 s/km de mieux que tes deux premières sorties, sur exactement la même distance." },
        { titre: "Le point d'attention : les pauses", texte: "Un point mérite quand même ton attention : 4 min 19 de pause sur cette séance, contre quasiment rien les fois précédentes. Le chrono affiché ne compte que le temps en mouvement, donc l'allure est juste — mais boucler 5 km en plusieurs morceaux ou d'une traite, ce n'est pas le même exercice pour l'organisme." },
        { titre: "La continuité avant les secondes", texte: "Si la coupure était subie, la prochaine fois vise plutôt à la raccourcir qu'à tenir l'allure : c'est la continuité de l'effort qui construit l'endurance, bien plus que les secondes au kilomètre." },
      ],
      pokemon: "Canarticho", pokemonAdj: "Distrait",
      pokemonPhrase: "Canarticho : il court en tenant un poireau, ce qui explique assez bien 4 minutes et 19 secondes de pause au milieu d'un 5 km. Distrait, parce que c'est précisément le temps qu'il faut pour retrouver le poireau qu'on a posé quelque part." },
    "2026-08-01": { trend: "flat", verdict: "Même allure, sans les coupures",
      text: [
        { titre: "Même chrono, sans les coupures", texte: "Rigoureusement la même allure qu'il y a deux jours (6'28\"/km), mais cette fois presque sans t'arrêter : 30 secondes de pause contre 4 min 19." },
        { titre: "Mieux que ce que dit le chrono", texte: "C'est une meilleure séance que la précédente, même si le chrono refuse de le dire — tenir 32 minutes d'affilée demande davantage que tenir la même allure entrecoupée de récupérations. Le conseil de la dernière fois a été appliqué en une séance, et ça se voit." },
      ],
      pokemon: "Herbizarre", pokemonAdj: "Discipliné",
      pokemonPhrase: "Herbizarre : il ne fait jamais rien de spectaculaire, il se contente de pousser tranquillement dans son coin. Deux secondes de mieux au chrono et quatre minutes de pause en moins, c'est très exactement sa méthode. Discipliné, parce qu'il a appliqué la consigne en une seule séance, sans négocier et sans faire de bruit." },
    "2026-08-05": { trend: "up", verdict: "Record + gros coup d'accélérateur",
      text: [
        { titre: "Sous les 32 minutes", texte: "Nouveau record : 6'19\"/km, 9 s/km grattées, et ton 5 km passe sous les 32 minutes (31:42)." },
        { titre: "13,9 km/h, le chiffre qui saute", texte: "Le chiffre qui saute aux yeux, c'est la vitesse de pointe : 13,9 km/h, contre 10,4 à 11,0 sur absolument toutes tes autres sorties. Tu as lâché les chevaux sur une portion, très probablement la fin." },
        { titre: "Les pointes ne font pas le progrès", texte: "C'est excellent pour découvrir ce que tu as sous le pied, à condition que ça reste l'exception : l'essentiel du progrès vient des kilomètres roulés à allure régulière, pas des pointes." },
      ],
      pokemon: "Voltorbe", pokemonAdj: "Explosif",
      pokemonPhrase: "Voltorbe : immobile, immobile, immobile, et d'un coup tout part en même temps. 13,9 km/h de pointe après cinq séances à 11, c'est littéralement son mode de fonctionnement. Explosif, parce que cinq sorties à 11 km/h puis d'un coup 13,9, ce n'est plus une accélération, c'est un blast beat au milieu d'une ballade." },
    "2026-08-09": { trend: "up", verdict: "Troisième record, et le plus propre",
      text: [
        { titre: "Un record sans sprint final", texte: "Encore un record, et le mieux construit des trois : 5,00 km en 31:29, soit 6'17\"/km. Le gain est plus fin que la dernière fois (2 s/km contre 9), mais la manière est meilleure — pointe à 11,2 km/h seulement, donc pas de sprint final pour aller chercher le chrono, juste une allure tenue de bout en bout." },
        { titre: "17 s/km en dix-sept jours", texte: "En dix-sept jours, ton allure est passée de 6'34\" à 6'17\", soit 17 s/km, sur une distance strictement identique à chaque sortie. C'est le protocole le plus honnête qui existe pour mesurer un progrès : même parcours, même distance, seul le temps bouge." },
        { titre: "Prochaine étape : allonger", texte: "Prochaine étape logique maintenant que les 5 km sont acquis : allonger, 6 ou 7 km à allure franchement tranquille, pour élargir la base avant de rechercher la vitesse." },
      ],
      pokemon: "Persian", pokemonAdj: "Impérial",
      pokemonPhrase: "Persian : rapide, silencieux, et absolument pas du genre à se donner en spectacle. Troisième record d'affilée sans jamais dépasser 11,2 km/h, c'est la classe à la Persian. Impérial, parce que gagner sans même avoir besoin d'accélérer, c'est la démarche de quelqu'un qui sait très bien qu'on le regarde." },
  },
  // Ju : pas encore de séance, donc pas encore d'analyse.
  Ju: {},
};
