// Données des sessions de course — extraites des captures Apple Fitness.
// Allure en secondes/km pour permettre les calculs/graphiques.
// Durée en secondes. Distance en km. Dénivelé en m. FC en bpm. Cadence en spm.

const RUNS = {
  Vincent: [
    { date: "2026-05-16", duration: 1893, distance: 3.74, activeCal: 268, totalCal: 324, elevation: 13, cadence: 123, paceSec: 505, hr: 133 },
    { date: "2026-05-17", duration: 1877, distance: 3.80, activeCal: 268, totalCal: 322, elevation: 7,  cadence: 122, paceSec: 494, hr: 132 },
    { date: "2026-05-23", duration: 1844, distance: 3.79, activeCal: 261, totalCal: 315, elevation: 4,  cadence: 121, paceSec: 486, hr: 128 },
    { date: "2026-05-27", duration: 1918, distance: 3.72, activeCal: 258, totalCal: 314, elevation: 10, cadence: 121, paceSec: 515, hr: 127 },
    { date: "2026-05-30", duration: 1937, distance: 3.95, activeCal: 282, totalCal: 338, elevation: 6,  cadence: 123, paceSec: 490, hr: 135 },
    { date: "2026-06-09", duration: 1896, distance: 3.77, activeCal: 261, totalCal: 317, elevation: 6,  cadence: 124, paceSec: 503, hr: 135 },
    { date: "2026-06-11", duration: 1712, distance: 3.62, activeCal: 256, totalCal: 306, elevation: 9,  cadence: 126, paceSec: 472, hr: 137 },
    { date: "2026-06-14", duration: 1868, distance: 4.05, activeCal: 287, totalCal: 342, elevation: 10, cadence: 126, paceSec: 461, hr: 138 },
    { date: "2026-06-20", duration: 2124, distance: 4.63, activeCal: 334, totalCal: 396, elevation: 7,  cadence: 127, paceSec: 458, hr: 139 },
    { date: "2026-06-23", duration: 2053, distance: 4.55, activeCal: 327, totalCal: 387, elevation: 6,  cadence: 129, paceSec: 451, hr: 143 },
    { date: "2026-06-26", duration: 2180, distance: 4.84, activeCal: 346, totalCal: 410, elevation: 6,  cadence: 131, paceSec: 450, hr: 142 },
    { date: "2026-06-28", duration: 2286, distance: 5.15, activeCal: 367, totalCal: 434, elevation: 10, cadence: 132, paceSec: 443, hr: 144 },
    { date: "2026-07-01", duration: 2113, distance: 4.85, activeCal: 351, totalCal: 413, elevation: 8,  cadence: 134, paceSec: 435, hr: 149 },
    { date: "2026-07-05", duration: 2157, distance: 4.88, activeCal: 343, totalCal: 407, elevation: 9,  cadence: 131, paceSec: 442, hr: 138 },
    { date: "2026-07-07", duration: 2242, distance: 5.17, activeCal: 369, totalCal: 434, elevation: 6,  cadence: 134, paceSec: 433, hr: 148 },
    { date: "2026-07-10", duration: 1969, distance: 4.70, activeCal: 343, totalCal: 400, elevation: 6,  cadence: 137, paceSec: 419, hr: 143 },
    { date: "2026-07-17", duration: 2228, distance: 5.39, activeCal: 389, totalCal: 455, elevation: 10, cadence: 136, paceSec: 413, hr: 148 },
    { date: "2026-07-25", duration: 1985, distance: 5.04, activeCal: 373, totalCal: 431, elevation: 7,  cadence: 143, paceSec: 393, hr: 157 },
    { date: "2026-07-29", duration: 1944, distance: 5.01, activeCal: 372, totalCal: 428, elevation: 3,  cadence: 142, paceSec: 388, hr: 153 },
    { date: "2026-08-01", duration: 1926, distance: 5.01, activeCal: 376, totalCal: 432, elevation: 3,  cadence: 142, paceSec: 384, hr: 157 },
    { date: "2026-08-05", duration: 1881, distance: 5.01, activeCal: 375, totalCal: 430, elevation: 2,  cadence: 147, paceSec: 375, hr: 159 },
  ],
  "Anaïs": [
    { date: "2026-05-17", duration: 1856, distance: 3.76, activeCal: 173, totalCal: 211, elevation: 5,  cadence: 129, paceSec: 493, hr: 131 },
    { date: "2026-05-23", duration: 1882, distance: 3.68, activeCal: 164, totalCal: 202, elevation: 3,  cadence: 129, paceSec: 511, hr: 118 },
    { date: "2026-05-27", duration: 1918, distance: 3.64, activeCal: 155, totalCal: 194, elevation: 10, cadence: 125, paceSec: 527, hr: 111 },
    { date: "2026-05-30", duration: 1939, distance: 3.88, activeCal: 175, totalCal: 214, elevation: 6,  cadence: 125, paceSec: 499, hr: 124 },
    { date: "2026-06-09", duration: 1895, distance: 3.66, activeCal: 169, totalCal: 207, elevation: 6,  cadence: 126, paceSec: 517, hr: 124 },
    { date: "2026-06-14", duration: 1868, distance: 3.87, activeCal: 177, totalCal: 215, elevation: 12, cadence: 126, paceSec: 482, hr: 125 },
    { date: "2026-06-20", duration: 2123, distance: 4.47, activeCal: 206, totalCal: 249, elevation: 9,  cadence: 130, paceSec: 474, hr: 127 },
    { date: "2026-06-28", duration: 2285, distance: 4.86, activeCal: 233, totalCal: 280, elevation: 8,  cadence: 131, paceSec: 470, hr: 129 },
    { date: "2026-07-05", duration: 2146, distance: 4.47, activeCal: 211, totalCal: 254, elevation: 5,  cadence: 130, paceSec: 480, hr: 130 },
    { date: "2026-07-10", duration: 1969, distance: 4.22, activeCal: 200, totalCal: 240, elevation: 9,  cadence: 133, paceSec: 467, hr: 125 },
    { date: "2026-07-17", duration: 2234, distance: 4.80, activeCal: 234, totalCal: 280, elevation: 9,  cadence: 130, paceSec: 465, hr: 136 },
    { date: "2026-07-29", duration: 1947, distance: 4.48, activeCal: 225, totalCal: 265, elevation: 5,  cadence: 138, paceSec: 434, hr: 142 },
    { date: "2026-08-01", duration: 1978, distance: 4.57, activeCal: 226, totalCal: 266, elevation: 2,  cadence: 138, paceSec: 432, hr: 144 },
  ],
};

const RUNNER_COLORS = {
  Vincent: "#0a84ff",
  "Anaïs": "#ff375f",
};

// Analyses « coach » par séance, rédigées en comparant chaque run aux précédentes
// du MÊME coureur (jamais de mélange Vincent / Anaïs).
// trend : "up" (progrès) | "flat" (stable / volontairement facile) | "down" (en retrait) | "start" (1re séance)
// Contexte coureurs : Vincent 30 ans, Anaïs 29 ans — 9 ans de musculation chacun, très novices en cardio.
const ANALYSES = {
  Vincent: {
    "2026-05-16": { trend: "start", verdict: "Point de départ",
      text: "Première séance enregistrée : 3,74 km en 8'25\"/km à 133 bpm. C'est ta ligne de base. Avec 9 ans de muscu dans les jambes mais un cardio encore neuf, l'objectif des prochaines semaines n'est pas la vitesse mais d'habituer le cœur et le souffle à l'effort continu." },
    "2026-05-17": { trend: "up", verdict: "Déjà plus rapide",
      text: "Deux jours seulement après la première sortie, et déjà 11 s/km de gagnées (8'14\" contre 8'25\") pour une fréquence cardiaque identique. Enchaîner si vite montre une bonne récupération — un héritage direct de ton entraînement en force." },
    "2026-05-23": { trend: "up", verdict: "Cœur plus efficace",
      text: "Allure encore grignotée (8'06\"/km), mais surtout la FC moyenne baisse à 128 bpm alors que tu cours aussi vite. Le cœur travaille moins pour le même effort : c'est le premier vrai signe d'adaptation aérobie. Continue comme ça." },
    "2026-05-27": { trend: "flat", verdict: "Séance en souplesse",
      text: "Sortie plus tranquille : 8'35\"/km, la plus lente jusqu'ici, sur une distance raccourcie. Ta FC est au plus bas (127 bpm), donc c'est une séance facile assumée, pas un coup de moins bien. Ces sorties en aisance construisent l'endurance autant que les rapides." },
    "2026-05-30": { trend: "up", verdict: "Rebond + distance record",
      text: "Joli rebond : retour à 8'10\"/km et surtout ta plus longue distance à ce jour (3,95 km), tu frôles la barre des 4 km. Les calories montent avec le volume. Tu commences à tenir l'effort plus longtemps." },
    "2026-06-09": { trend: "flat", verdict: "Reprise après coupure",
      text: "Reprise après 10 jours de coupure : 8'23\"/km, un poil en retrait, ce qui est parfaitement normal après une pause. La FC reste un peu haute pour l'allure, le temps de retrouver le rythme. L'essentiel est d'être reparti." },
    "2026-06-11": { trend: "up", verdict: "Première sous les 8'/km",
      text: "Cap symbolique franchi : première sortie sous les 8'/km (7'52\") ! Tu as raccourci la distance pour pousser l'allure, et signé ta séance la plus courte en durée (28:32). La vitesse pure progresse nettement." },
    "2026-06-14": { trend: "up", verdict: "Plus vite ET plus loin",
      text: "Du costaud : plus vite (7'41\"/km) ET plus loin (4,05 km, nouveau record de distance) dans la même séance. D'habitude on gagne sur l'un en lâchant sur l'autre — là tu progresses sur les deux. Le moteur cardio se construit pour de bon." },
    "2026-06-20": { trend: "up", verdict: "Cap des 4,5 km",
      text: "Gros bond d'endurance : 4,63 km, ton record, en gardant une allure de 7'38\"/km. Plus de 35 min d'effort continu et 334 cal brûlées. Le cœur monte à 139 bpm mais tient la distance — exactement la progression attendue." },
    "2026-06-23": { trend: "up", verdict: "Record d'allure",
      text: "Nouveau record d'allure : 7'31\"/km sur 4,55 km, avec une cadence qui grimpe (129 spm), signe d'une foulée plus efficace. Tu cours désormais près d'une minute par km plus vite qu'à tes débuts de mai." },
    "2026-06-26": { trend: "up", verdict: "Presque 5 km",
      text: "Tout proche des 5 km : 4,84 km, record de distance, à 7'30\"/km (record d'allure égalé) et meilleure cadence (131 spm). Distance et vitesse continuent de monter ensemble. Le palier des 5 km est à portée de main." },
    "2026-06-28": { trend: "up", verdict: "Premier 5 km 🎉",
      text: "Le voilà, ton premier 5 km : 5,15 km en 7'23\"/km, record sur les deux tableaux ! En six semaines tu es passé de 3,7 km à 8'25\" à un vrai 5K à 7'23\". Pour un cardio parti de zéro, c'est une progression remarquable — ton fond musculaire a clairement accéléré l'adaptation." },
    "2026-07-01": { trend: "up", verdict: "Record d'allure",
      text: "Nouveau record d'allure : 7'15\"/km, soit 8 s/km de mieux que ton précédent meilleur (7'23\"). Sur une distance un peu plus courte (4,85 km), tu as clairement mis le gaz — FC à 149 bpm, ta plus haute, et cadence record de 134 spm. Après ton premier 5 km, tu travailles maintenant la vitesse : les deux se complètent parfaitement." },
    "2026-07-05": { trend: "flat", verdict: "Séance en aisance",
      text: "Retour à une allure plus tranquille (7'22\"/km) sur une distance quasi identique (4,88 km) à ton record du 1er juillet — mais avec 11 bpm de moins (138 contre 149). C'est le signe qu'après ta séance de vitesse, tu as sagement levé le pied : le cœur encaisse un effort proche pour un coût cardiaque bien moindre, preuve que l'adaptation continue même les jours plus faciles." },
    "2026-07-07": { trend: "up", verdict: "Double record !",
      text: "Grosse séance : nouveau record de distance (5,17 km, ton premier vrai dépassement du 5K) ET nouveau record d'allure (7'13\"/km, 2 s/km de mieux que ton précédent record) dans la même sortie. FC à 148 bpm, cadence au sommet (134 spm) — tu as clairement tout donné (effort ressenti « Hard »). Deux semaines après ton premier 5 km, tu cours maintenant plus loin ET plus vite en même temps : la progression s'accélère." },
    "2026-07-10": { trend: "up", verdict: "Record d'allure... en mode facile",
      text: "Le plus bluffant : nouveau record d'allure (6'59\"/km, 14 s/km de mieux que ton précédent record de mardi), sous la barre symbolique des 7'/km, mais avec un effort ressenti « Moderate » (contre « Hard » la dernière fois) et une FC plus basse (143 contre 148). Cadence record aussi (137 spm). Ce qui était une allure à fond il y a encore quelques semaines devient une allure confortable — c'est exactement la marque d'une vraie adaptation cardio." },
    "2026-07-17": { trend: "up", verdict: "Encore un double record",
      text: "Après une semaine de pause, tu reviens avec un double record : plus longue distance à ce jour (5,39 km) ET meilleure allure (6'53\"/km, 6 s/km de mieux que ton record du 10 juillet). Le tout ressenti « Moderate » malgré une FC à 148 bpm sur plus de 37 minutes d'effort. Deux mois après tes débuts à 3,7 km en 8'25\", tu enchaînes les sorties où distance et vitesse montent ensemble — la marge de progression est loin d'être épuisée." },
    "2026-07-25": { trend: "up", verdict: "Record pulvérisé : 6'33\"/km",
      text: "Ce n'est plus une progression, c'est un bond : 6'33\"/km, soit 20 s/km arrachées à ton record du 17 juillet — de loin ton plus gros saut d'allure depuis le début. Tu boucles tes 5 km en 33:05, ta séance la plus rapide sur cette distance, avec une cadence record de 143 spm (+7 d'un coup) : ta foulée est nettement plus vive. La FC à 157 bpm est la plus haute jamais enregistrée, donc tu es allé chercher loin — d'où l'intérêt de faire suivre celle-ci d'une sortie en aisance. Repère du chemin parcouru : le 16 mai tu courais à 8'25\"/km, tu as gagné près de 2 minutes par kilomètre en dix semaines." },
    "2026-07-29": { trend: "up", verdict: "Nouveau record… ressenti « Easy »",
      text: "La séance la plus parlante depuis tes débuts : encore un record d'allure (6'28\"/km, 5 s/km de mieux que le 25 juillet) et ton 5 km le plus rapide à ce jour (32:24), mais cette fois avec un effort ressenti « Easy » et une FC en baisse (153 contre 157 bpm). Aller plus vite en se fatiguant moins, c'est le signal d'adaptation le plus net qu'on puisse avoir. Ta cadence se stabilise à un haut niveau (142 spm) : la foulée vive du 25 juillet n'était pas un accident, elle est devenue ta norme. Deux mois et demi après tes 8'25\"/km du 16 mai, ton allure de course facile est désormais plus rapide que ton allure maximale de juin." },
    "2026-08-01": { trend: "up", verdict: "Trois records d'allure d'affilée",
      text: "Troisième record consécutif : 6'24\"/km, 4 s/km de mieux que le 29 juillet, sur exactement la même distance (5,01 km) — 18 secondes de moins sur le chrono, ton 5 km le plus rapide à ce jour (32:06). Les gains se resserrent après le bond de 20 s/km du 25 juillet, et c'est plutôt bon signe : tu n'es plus en phase de rattrapage, tu grattes des secondes sur une base déjà solide. Seul point à surveiller, la FC remonte à 157 bpm (contre 153) alors que le ressenti reste « Easy » — trois séances rapides en une semaine, ça mérite une sortie franchement lente pour laisser l'adaptation se fixer." },
    "2026-08-05": { trend: "up", verdict: "Quatrième record d'affilée : 6'15\"/km",
      text: "Quatre records consécutifs, et pas le plus petit : 6'15\"/km, 9 s/km de mieux que le 1er août sur exactement la même distance (5,01 km) — ton 5 km passe sous les 31:30 (31:21), soit 45 secondes gagnées en quatre jours. La cadence signe un nouveau sommet à 147 spm (+5 d'un coup), et c'est bien là que la vitesse est allée se chercher : une foulée plus vive, pas des enjambées plus longues. Un bémol quand même, le même que la dernière fois en plus marqué : la FC monte encore, 159 bpm, ta plus haute jamais enregistrée, et tu n'as toujours pas placé la sortie lente que je te suggérais. Quatre séances rapides d'affilée, ça finit par se payer — la prochaine, vise franchement l'aisance (autour de 7'/km, FC sous 145). Ça ne cassera rien de ce que tu as construit, au contraire : c'est ce qui permettra au record suivant d'arriver." },
  },
  "Anaïs": {
    "2026-05-17": { trend: "start", verdict: "Point de départ",
      text: "Première séance enregistrée : 3,76 km en 8'13\"/km à 131 bpm. C'est ta référence de départ. Comme pour toute débutante en cardio venant de la force, le plan est simple : laisser le cœur et le souffle s'habituer avant de chercher la vitesse." },
    "2026-05-23": { trend: "flat", verdict: "Effort mieux dosé",
      text: "L'allure ralentit un peu (8'31\"/km), mais regarde la FC : 118 bpm, soit 13 de moins qu'à la première sortie. Tu apprends à doser ton effort plutôt qu'à tout donner — exactement la bonne approche pour bâtir une base aérobie solide." },
    "2026-05-27": { trend: "flat", verdict: "Séance tout en contrôle",
      text: "Séance tout en contrôle : 8'47\"/km, mais une FC moyenne de seulement 111 bpm, ta plus basse. Tu cours en grande aisance respiratoire. Ces sorties faciles ne paient pas tout de suite au chrono, mais elles posent les fondations de l'endurance." },
    "2026-05-30": { trend: "up", verdict: "Accélération + record",
      text: "Belle accélération : 8'19\"/km (28 s/km de gagnées) sur ta plus longue distance à ce jour (3,88 km). La FC remonte logiquement à 124 bpm puisque tu pousses davantage. Tu commences à transformer la base construite en vitesse." },
    "2026-06-09": { trend: "flat", verdict: "Reprise après coupure",
      text: "Reprise après 10 jours sans courir : 8'37\"/km, un léger retrait bien normal après une coupure. Distance et FC restent dans tes standards. L'essentiel est d'avoir relancé la machine — la forme revient vite." },
    "2026-06-14": { trend: "up", verdict: "Record d'allure",
      text: "Record d'allure : 8'02\"/km, soit 35 s/km de mieux que la séance précédente, ta meilleure performance jusqu'ici. Et tout ça à FC quasi inchangée (125 bpm) : le même effort te fait désormais aller bien plus vite. L'adaptation cardio porte ses fruits." },
    "2026-06-20": { trend: "up", verdict: "Sous 8' et cap des 4 km",
      text: "Double cap franchi : ta première sortie sous les 8'/km (7'54\") et ton record de distance (4,47 km, +0,6 km d'un coup). Plus de 35 min d'effort, 206 cal. Distance et vitesse progressent ensemble — pour un cardio parti de novice, la marche est nette." },
    "2026-06-28": { trend: "up", verdict: "Double record",
      text: "Double record d'un coup : 4,86 km (ta plus longue distance) à 7'50\"/km (ta meilleure allure, 4 s/km de mieux que le 20 juin). Et tout ça pour seulement 129 bpm de moyenne, à peine plus qu'avant : tu cours désormais plus loin ET plus vite sans que le cœur s'emballe. Le cap des 5 km est à portée." },
    "2026-07-05": { trend: "down", verdict: "Petit coup de mou",
      text: "Séance plus difficile : distance en retrait (4,47 km contre 4,86 km) et allure ralentie (8'00\"/km contre 7'50\"), pour une FC quasi identique (130 bpm). Après deux belles sorties records, ce genre de petit passage à vide est normal — le corps encaisse et régule sa charge d'entraînement. Rien d'inquiétant, la tendance de fond reste très positive." },
    "2026-07-10": { trend: "up", verdict: "Record d'allure au petit matin",
      text: "Le coup de mou du 5 juillet est déjà oublié : record d'allure à 7'47\"/km (3 s/km de mieux que ton précédent record du 28 juin), et surtout avec une FC de seulement 125 bpm, bien plus basse que tes dernières sorties à 129-130. Courir plus vite avec un cœur plus calme, c'est la définition même de l'adaptation aérobie. La cadence record (133 spm) montre aussi une foulée qui s'affine." },
    "2026-07-17": { trend: "up", verdict: "Encore un record d'allure",
      text: "Deuxième record d'allure d'affilée : 7'45\"/km, sur une distance bien plus longue que la semaine dernière (4,80 km, tout proche de ton record de 4,86 km). Tu tiens maintenant ta meilleure allure sur quasi 5 km — il y a un mois, elle n'était possible que sur des sorties plus courtes. La FC monte logiquement à 136 bpm avec le volume, mais le cap des 5 km à cette allure est clairement à ta portée." },
    "2026-07-29": { trend: "up", verdict: "Énorme bond : 7'14\"/km",
      text: "Ton plus gros saut d'allure depuis le début : 7'14\"/km, soit 31 s/km arrachées à ton record du 17 juillet — après des progrès qui se comptaient en 3 ou 4 secondes, tu viens de franchir une marche entière. La cadence explose au passage (138 spm, +5 sur ton précédent record) : c'est là qu'est venue la vitesse, une foulée bien plus vive plutôt que des enjambées forcées. La FC à 142 bpm est la plus haute que tu aies enregistrée et la distance est volontairement plus courte (4,48 km) : c'était une séance de vitesse assumée, à faire suivre d'une sortie en aisance. Le chemin parcouru fait plaisir à voir — le 17 mai tu courais à 8'13\"/km, tu as gagné près d'une minute par kilomètre en dix semaines." },
    "2026-08-01": { trend: "up", verdict: "Le bond du 29 juillet confirmé",
      text: "La question après ton énorme saut du 29 juillet était : est-ce que ça tient ? Réponse oui — nouveau record d'allure à 7'12\"/km (2 s/km de mieux), et cette fois sur une distance plus longue (4,57 km contre 4,48). Tenir sa meilleure allure sur plus de terrain, c'est la vraie preuve qu'un progrès s'est installé plutôt qu'un bon jour isolé. La cadence reste calée à 138 spm et la FC bouge à peine (144 contre 142) : ta foulée vive est devenue automatique. Tes splits racontent bien la séance — départ à 6'51\", puis stabilisation autour de 7'12-7'26\" : tu es partie un peu vite, essaie de lisser sur la prochaine, tu finiras plus fraîche." },
  },
};
